#include "pch.h"

#include "LookupTables.h"

/*
 * GENERATED by tools/extract_tables.py -- do not edit by hand.
 *
 * Extracted by label and length from the assembled Commodore 64 build. The companion
 * test compares every array here against the same address range in the oracle's image,
 * so an edit or a stale regeneration fails rather than drifting quietly.
 */

namespace Elite
{
// 6502: ACT -- arctangent, indexed by a ratio.
const std::array<std::uint8_t, 32> ARCTAN_TABLE = {
  0x00, 0x01, 0x03, 0x04, 0x05, 0x06, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D,
  0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x19,
  0x1A, 0x1B, 0x1C, 0x1D, 0x1D, 0x1E, 0x1F, 0x1F,
};

} // namespace Elite
