// GameLogic/DataOverlay.h
// Generated by Tools/GenerateOverlay.py from Design/Symbols.tsv. Do not edit: change the symbol table
// and run the tool again (ADR-010).
#pragma once

#include "DataField.h"

#include <cstdint>

namespace Elite
{

/// The reference's data segment by name (plan §3, ADR-010): one field for every data, table and text
/// row of the symbol table, at its offset. Native code reads and writes through Guest with these.
struct DataOverlay
{
  /// the space view, rows 1-126 of a 256x128 2bpp buffer at DS:0000-1FFF (64 bytes a row); the drawing routines also write rows 0 and...
  DataBlock<8064> spaceViewBuffer{0x0040};
  /// 1 in the file; cleared at start-up unless the ROM at FC00:0016 reads Amstrad
  DataField<std::uint8_t> amstradPresent{0x2000};
  /// Amstrad
  DataBlock<7> amstradSignature{0x2001};
  /// the value last written to port 0x61; the timer handler toggles bit 1 for sound effects
  DataField<std::uint8_t> speakerPortImage{0x2008};
  /// what ShowDiscControlScreen asks Start to do, written at 0x7E90: 0 Exit to DOS (Start calls WipeProgram at 0x0072, then exits), 1...
  DataField<std::uint8_t> diskOperation{0x2009};
  /// $-terminated, int 21h AH=09
  DataAt exitMessage{0x200A};
  /// $-terminated
  DataAt dosVersionMessage{0x2039};
  /// ' cheat' with every byte XOR 0xAA
  DataBlock<6> cheatArgumentKey{0x2063};
  /// DS at entry; CheckCheatArgument reads the command tail from pspSegment:0080
  DataField<std::uint16_t> pspSegment{0x2069};
  /// 1 when the command tail is exactly ' cheat' (CheckCheatArgument compares PSP:80h with DS:2063 XOR AAh); RunFlight then ignores th...
  DataField<std::uint8_t> cheatEnabled{0x206B};
  /// set by CriticalErrorInterrupt (0x02F6) and PerformDiskRequest's error path (0x03A2), cleared by Start (0x0078) before each operation
  DataField<std::uint8_t> diskError{0x206C};
  /// DOS handle of the open commander or screenshot file
  DataField<std::uint16_t> fileHandle{0x206D};
  /// int 21h AH=1Ah buffer; find-first/next put the attribute at DS:2084 and the name at DS:208D
  DataBlock<43> diskTransferArea{0x206F};
  /// *.cdr
  DataBlock<6> commanderFilePattern{0x20EF};
  /// file names without extension, NUL-terminated, written by PerformDiskRequest's catalogue
  DataAt commanderFileList{0x20F5};
  /// names in commanderFileList, capped at 40 (0x03E3)
  DataField<std::uint8_t> commanderFileCount{0x2267};
  /// write pointer into commanderFileList
  DataField<std::uint16_t> commanderFileListNext{0x2268};
  /// port 0x61 at start-up, restored on exit
  DataField<std::uint8_t> savedSpeakerPort{0x226A};
  /// BIOS int 0 vector
  DataBlock<4> savedDivideVector{0x226B};
  /// segment half of savedDivideVector
  DataField<std::uint16_t> data226D{0x226D};
  /// BIOS int 9 vector
  DataBlock<4> savedKeyboardVector{0x226F};
  /// segment half of savedKeyboardVector
  DataField<std::uint16_t> data2271{0x2271};
  /// 'elite' + two digits + '.lo', for the text layout
  DataBlock<11> screenshotTextFileName{0x2273};
  /// the two digits in screenshotTextFileName
  DataField<std::uint16_t> screenshotTextFileDigits{0x2278};
  /// 'elite' + two digits + '.hi', for the graphics layouts
  DataBlock<11> screenshotGraphicsFileName{0x227E};
  /// the two digits in screenshotGraphicsFileName
  DataField<std::uint16_t> screenshotGraphicsFileDigits{0x2283};
  /// two ASCII digits, '00' in the file, incremented before each screenshot
  DataField<std::uint16_t> screenshotNumber{0x2289};
  /// 'DISC ERROR'
  DataBlock<11> diskErrorText{0x228B};
  /// pointer to the protection's strings and question table
  DataField<std::uint16_t> protectionDescriptor{0x2416};
  /// field +0x0A of the protection descriptor (DS:2418), 0xA5D0; read at 0x73AF. The one word below DS:4D70 that differs from ELITEL.E...
  DataField<std::uint16_t> protectionAnswerListPointer{0x2422};
  /// Program Protection
  DataAt protectionTitle{0x2424};
  /// int 21h AH=0Ah buffer: capacity, count, then the typed word
  DataAt protectionInput{0x25C9};
  DataField<std::uint8_t> data25CA{0x25CA};
  /// question number while one is pending; 0xFF when none
  DataField<std::uint8_t> protectionQuestion{0x25E1};
  /// 3 in the file
  DataField<std::uint8_t> protectionTriesLeft{0x25E2};
  /// set by CheckProtectionAnswer; forced by the crack
  DataField<std::uint8_t> protectionAnswerCorrect{0x25E3};
  /// 0 in the file; the D5 patch sets it to 1 at load
  DataField<std::uint8_t> protectionShown{0x25E4};
  /// Amstrad only: ticks to the next chain to the BIOS int 8; reloaded with 55 or 18
  DataField<std::uint8_t> biosTimerChainCountdown{0x25E5};
  /// byte; laser mount number per view index (viewAngle/0x200): 1, 4, 2, 3 for front, left, rear, right
  DataTable<1, 4> viewLaserMount{0x25F0};
  /// sprite: 16 rows of an AND word pair then an OR word pair; one 128-byte 16x16 sight per laser type, drawn by DrawLaserSights; ends...
  DataAt laserSights{0x25F4};
  /// drawColor for stardust; 3 in the file
  DataField<std::uint8_t> stardustColor{0x27F4};
  /// 6-byte particle; +0 x, +2 y (signed words, on screen while the high bytes are -0x20..0x1F and -0x10..0x0F), +4 byte 0x28-0x47 (th...
  DataTable<6, 30> stardust{0x27F5};
  /// 6-byte particle; stardust+0xB4: start-of-frame copy for streaks; +5 is 1 for a particle respawned this frame
  DataTable<6, 30> stardustPrevious{0x28A9};
  /// written by ComputeStardustShift; 4 at full playerSpeed
  DataField<std::uint8_t> stardustShift{0x295D};
  /// toggled each shot of a type 0 or 2 laser: left or right pair
  DataField<std::uint8_t> laserBeamSide{0x295E};
  /// XORed with 2 each shot of a type 3 laser
  DataField<std::uint8_t> laserBeamColorToggle{0x295F};
  /// cycles through 1-3
  DataField<std::uint8_t> laserBeamColor{0x2960};
  /// first word of the seeds of the system being generated; its high byte is systemY
  DataField<std::uint16_t> systemSeed0{0x2970};
  /// the system's y, 0-255; the charts plot y/2
  DataField<std::uint8_t> systemY{0x2971};
  /// low byte bits 3-5 are the government; high byte is systemX
  DataField<std::uint16_t> systemSeed1{0x2972};
  /// the system's x, 0-255
  DataField<std::uint8_t> systemX{0x2973};
  /// low byte bit 7 clear means human colonials; bit 0 adds 1 to the tech level
  DataField<std::uint16_t> systemSeed2{0x2974};
  /// bits 0-4 pick the name digrams; species bits
  DataField<std::uint8_t> systemSeed2High{0x2975};
  /// 6-byte seed; system 0 of each galaxy; the first is 5A4A 0248 B753
  DataTable<6, 8> galaxySeeds{0x2976};
  /// 'Distance: 100.0 Light Years'; ShowNearestSystemDistance patches the digits at +0x0A-0x0C and +0x0E
  DataAt distanceText{0x29AC};
  /// 27 spaces and a NUL; ClearChartTextLines prints it twice
  DataBlock<28> blankChartLine{0x29C8};
  /// FormatDecimal5's five ASCII digits of selectedDistanceTenthsLy
  DataBlock<5> distanceDigits{0x29E4};
  DataField<std::uint8_t> distanceHundredsDigit{0x29E5};
  DataField<std::uint8_t> distanceTensDigit{0x29E6};
  DataField<std::uint8_t> distanceUnitsDigit{0x29E7};
  DataField<std::uint8_t> distanceTenthsDigit{0x29E8};
  /// FindSystemByName's typed name, 8 characters and a terminator
  DataBlock<9> findInput{0x29E9};
  /// the name as typed, for the error message
  DataBlock<9> findInputEcho{0x29F2};
  /// 12 spaces printed after a system name
  DataAt nameLinePadding{0x29FB};
  /// 'FIND: Which System ?'
  DataAt findPrompt{0x2A08};
  /// 2 characters; entry 0 is two spaces, which add nothing
  DataTable<2, 32> systemNameDigrams{0x2A1D};
  /// 'SHORT RANGE CHART'
  DataAt shortRangeChartTitle{0x2A5D};
  /// 'GALACTIC CHART ' then galacticChartNumber
  DataAt galacticChartTitle{0x2A6F};
  /// '1' + galaxyNumber
  DataField<std::uint8_t> galacticChartNumber{0x2A7E};
  /// 'ERROR: '
  DataAt findErrorPrefix{0x2A81};
  /// ' not on map!'
  DataAt findErrorSuffix{0x2A89};
  /// items in chartItems: stars first, then labels added by AddChartLabel
  DataField<std::uint8_t> chartItemCount{0x2A96};
  /// address of the next free 8-byte item in chartItems
  DataField<std::uint16_t> chartItemEnd{0x2A97};
  /// 8 bytes: x min, x max, row min, row max, word centre or text, byte size, byte is-label; the short-range chart's occupied rectangl...
  DataTable<8, 32> chartItems{0x2A99};
  /// next pending label in pendingChartLabels; AddChartLabel moves it past the name
  DataField<std::uint16_t> chartLabelCursor{0x2B99};
  /// records of word x range, word row range, NUL-terminated system name, written by ShowShortRangeChart
  DataAt pendingChartLabels{0x2B9B};
  /// tries so far for the current label; NudgeChartLabel gives up at 35
  DataField<std::uint8_t> labelNudgeCount{0x2C9B};
  /// counted down by PlaceChartLabels
  DataField<std::uint8_t> labelsLeftToPlace{0x2C9C};
  /// HandleFlightFunctionKeys: a screen replaced the cockpit, so it must be restored
  DataField<std::uint8_t> flightScreenShown{0x2C9D};
  /// 'Nav-Comp Error... WITCH SPACE!'
  DataAt navCompErrorMessage{0x2C9E};
  /// word: low byte fill mask, high byte keep mask; indexed by x&3 for a span's first byte (FillSpan)
  DataTable<2, 4> spanLeftMasks{0x2CC0};
  /// word: low byte fill mask, high byte keep mask; indexed by x&3 for a span's last byte (FillSpan)
  DataTable<2, 4> spanRightMasks{0x2CC8};
  /// 4 bytes, one per row; discs of radius 1-4 drawn by DrawSmallDisc
  DataTable<4, 4> smallDiscSprites{0x2CD0};
  /// byte; 00 55 AA FF: colour 0-3 repeated across a byte's four pixels
  DataTable<1, 4> colorFillBytes{0x2CE0};
  /// colour 0-3 for the line and circle drawers (DrawDisc indexes the pattern bytes at DS:2CE0 with it); the title sets 2, ApplyEnemyL...
  DataField<std::uint8_t> drawColor{0x2CE4};
  /// colorFillBytes[drawColor], set by DrawDisc for FillSpan
  DataField<std::uint8_t> discFillByte{0x2CE5};
  /// DrawDisc's centre x
  DataField<std::uint16_t> discCenterX{0x2CE6};
  /// DrawDisc's radius/2: the rows above and below the centre
  DataField<std::uint8_t> discRadiusRows{0x2CE8};
  /// DrawDisc's row counter
  DataField<std::uint8_t> discRowsLeft{0x2CE9};
  /// fractional step through circleProfile per row (0x20000/rows)
  DataField<std::uint16_t> discProfileStepFraction{0x2CEA};
  /// whole-byte step through circleProfile per row
  DataField<std::uint16_t> discProfileStepWhole{0x2CEC};
  /// byte; 255*sqrt(1-(i/512)^2): a disc's half-width per row from the centre outwards
  DataTable<1, 513> circleProfile{0x2CEE};
  /// Fibonacci generator state with fringeRandomB: (a,b) becomes (b,a+b)
  DataField<std::uint16_t> fringeRandomA{0x2EEF};
  /// its high byte AND sunFringeMask is added to each half-width
  DataField<std::uint16_t> fringeRandomB{0x2EF1};
  /// read by DrawDisc as an AND mask on the disc fill: DrawSunOrPlanet sets 1/3/7 for the sun as its radius passes 0x28/0xB4, 0 for th...
  DataField<std::uint8_t> sunFringeMask{0x2EF3};
  /// 2 bytes: x, y at radius 127; points at 0, 11.25, 22.5 and 33.75 degrees for DrawCircle
  DataTable<2, 4> circleOctant{0x2EF4};
  /// 2 words: x, y; DrawCircle's polygon
  DataTable<4, 32> circlePoints{0x2EFC};
  DataField<std::uint16_t> data2EFE{0x2EFE};
  /// FillTriangle: apex x (flat bottom), B.x (flat top) or top x (general)
  DataField<std::uint8_t> triangleEdgeStartX{0x2F7C};
  /// FillTriangle: apex x, C.x, or top x
  DataField<std::uint8_t> triangleEdgeStartX2{0x2F7D};
  /// the lowest row, where DrawStackedSpans starts; FillClippedOneRow writes the row byte too
  DataField<std::uint8_t> triangleBottomRow{0x2F7E};
  /// rows from top to the lower vertex (flat) or to the middle vertex (general)
  DataField<std::uint8_t> triangleUpperRows{0x2F80};
  /// general triangle: rows from top to bottom
  DataField<std::uint8_t> triangleTotalRows{0x2F81};
  /// general triangle: middle vertex x
  DataField<std::uint8_t> triangleMiddleX{0x2F82};
  /// general triangle: bottom vertex x
  DataField<std::uint8_t> triangleBottomX{0x2F83};
  /// written by DrawVisibleFaces (0x3B38) from faceFillPatterns, read by DrawStackedSpansFromRow (0x1CDD): low byte on even rows, high...
  DataField<std::uint16_t> triangleFillPattern{0x2F84};
  /// FillClippedTriangle: first edge start x (apex, B.x or top)
  DataField<std::uint16_t> clippedEdgeStartX{0x2F86};
  /// FillClippedTriangle: second edge start x (apex, C.x or top)
  DataField<std::uint16_t> clippedEdgeStartX2{0x2F88};
  /// rows to the lower (flat) or middle (general) vertex
  DataField<std::uint16_t> clippedUpperRows{0x2F8A};
  /// general: rows top to bottom
  DataField<std::uint16_t> clippedTotalRows{0x2F8C};
  /// first drawn row; 0x8000 = none yet
  DataField<std::uint16_t> clippedFirstRow{0x2F8E};
  /// last drawn row; written, never read
  DataField<std::uint16_t> clippedLastRow{0x2F90};
  /// 16.16 slope of edge A or the long edge, fraction word (second div)
  DataField<std::uint16_t> clippedSlopeAFraction{0x2F92};
  /// its integer word (first div)
  DataField<std::uint16_t> clippedSlopeAWhole{0x2F94};
  /// 16.16 slope of edge B or the short edge, fraction word
  DataField<std::uint16_t> clippedSlopeBFraction{0x2F96};
  /// its integer word
  DataField<std::uint16_t> clippedSlopeBWhole{0x2F98};
  /// general: middle vertex x
  DataField<std::uint16_t> clippedMiddleX{0x2F9A};
  /// general: bottom vertex x
  DataField<std::uint16_t> clippedBottomX{0x2F9C};
  /// general: rows drawn, the span count for DrawStackedSpansFromRow
  DataField<std::uint8_t> clippedRowCount{0x2F9E};
  /// word; 16384*sin(2*pi*i/2048), +-1; SetSinCos reads sin at i and cos at i+512 (and 0x7FF); BuildDodoVertices reads high bytes at D...
  DataTable<2, 2048> sineTable{0x2FA0};
  /// word; tan(i*45/256 degrees)*32768, binary-searched by RatioArcTangent
  DataTable<2, 256> tangentTable{0x3FA0};
  /// word sin, word cos; filled by the entries 2421/2426/242B/2430/2435/243B/2441/244D/2447 (one each), used by the rotations 2453..24...
  DataTable<4, 9> rotationSinCos{0x41A0};
  /// 50 in the file; ProjectVertices marks vertices nearer than this with x=0x8000
  DataField<std::uint16_t> nearPlaneZ{0x41CE};
  /// set to 1 when an ECM goes off: NPC (0x566E) or the player's E key with ecmFitted (0x82AD); read and cleared at 0x257D, which pick...
  DataField<std::uint8_t> ecmFired{0x41F0};
  /// the sun's apparent radius from DrawSunOrPlanet; CheckTemperatureWarning at >= 0xE1
  DataField<std::uint8_t> cabinTemperature{0x41F1};
  /// +5 per shot, saturating at FFh; the fire button does nothing at F0h or above
  DataField<std::uint8_t> laserTemperature{0x41F2};
  /// 2*min(127, 255 - planet radius) from DrawSunOrPlanet; 0xFF at launch (29D0); CheckAltitudeWarning below 0x32
  DataField<std::uint8_t> altitude{0x41F3};
  /// drawn on the top dashboard bar (2614, cell 368Ch, the FORE-SHIELD row); ApplyEnemyLaserHit takes 15 off it
  DataField<std::uint8_t> foreShield{0x41F4};
  /// drawn on the AFT-SHIELD bar (2623, cell 37CCh)
  DataField<std::uint8_t> aftShield{0x41F5};
  /// 0-3FFh; DrainEnergy, UseMaskingDevice and ApplyEnemyLaserHit take from it, below 0 sets playerDead; CheckEnergyWarning below 0x10...
  DataField<std::uint16_t> playerEnergy{0x41F8};
  /// byte; the partial byte of a bar: 1, 2 or 3 pixels of colour 1 then colour 2 (entry 0 unused)
  DataTable<1, 4> barPartialBytes{0x41FA};
  /// word; DrawSignedIndicator's 2-pixel marker at each pixel offset
  DataTable<2, 4> indicatorMarkers{0x41FE};
  /// word, one per scanline; drawn by DrawMissileIcons in the order +0, +4, +8, +2, +6 to match the CGA banks
  DataTable<2, 5> missileIcon{0x4206};
  /// word, one per scanline; an 8x8 disc, ANDed with the condition colour
  DataTable<2, 8> conditionLightBitmap{0x4210};
  /// 0 idle, 1 primed and looking for a target (T or I), 2 locked on missileTarget; also the colour index DrawMissileLockIndicator draws
  DataField<std::uint8_t> missileState{0x4220};
  /// 1 green, 3 yellow, 2 red, 0 flashing red; written by UpdateConditionColor
  DataField<std::uint8_t> conditionColor{0x4221};
  /// first of the 22 dashboard cache bytes DS:4222-4237 that InvalidateDashboard sets to 0x80
  DataField<std::uint8_t> missileCountShown{0x4222};
  /// dashboard cache of missileState
  DataField<std::uint8_t> missileLockShown{0x4223};
  /// byte; dashboard cache of energyBankFill
  DataTable<1, 4> energyBanksShown{0x4224};
  /// byte; per-bank fill computed by DrawEnergyBanks from playerEnergy, bottom bank last
  DataTable<1, 4> energyBankFill{0x4228};
  /// dashboard cache
  DataField<std::uint8_t> rollRateShown{0x422C};
  /// dashboard cache
  DataField<std::uint8_t> pitchRateShown{0x422D};
  /// dashboard cache
  DataField<std::uint8_t> altitudeShown{0x422E};
  /// dashboard cache
  DataField<std::uint8_t> cabinTemperatureShown{0x422F};
  /// dashboard cache
  DataField<std::uint8_t> fuelShown{0x4230};
  /// dashboard cache: 0x20 or 0x81
  DataField<std::uint8_t> ecmGlyphShown{0x4231};
  /// dashboard cache: 0x20 or 0x82
  DataField<std::uint8_t> safeZoneGlyphShown{0x4232};
  /// dashboard cache
  DataField<std::uint8_t> laserTemperatureShown{0x4233};
  /// compared but never written by UpdateDashboard, so the fore shield bar is redrawn every frame unless the shield is 0x80
  DataField<std::uint8_t> foreShieldShown{0x4234};
  /// compared but never written, as foreShieldShown
  DataField<std::uint8_t> aftShieldShown{0x4235};
  /// dashboard cache
  DataField<std::uint8_t> conditionColorShown{0x4236};
  /// dashboard cache
  DataField<std::uint8_t> speedShown{0x4237};
  /// 'Equipment Loss due to Low Energy'
  DataAt equipmentLossMessage{0x4238};
  /// slot of the ship whose laser hit the player (51C3)
  DataField<std::uint16_t> playerHitBy{0x4260};
  /// set to 2 or 1 by the enemy fire code (51C7, 51DA); ApplyEnemyLaserHit applies it and clears it
  DataField<std::uint8_t> playerHitPending{0x4262};
  /// 1 after a successful dock (0x2C4F), 0 at 0x2A11; ShowCommanderStatusScreen debriefs only when it is 1
  DataField<std::uint8_t> playerDocked{0x4263};
  /// word; box half-size per object type for CheckCollisions: 275 for types 0-1 (stations), 100 for the rest
  DataTable<2, 32> collisionRanges{0x4264};
  /// 5 points of 2 signed bytes; the tunnel's rectangles, smallest first, drawn by DrawTunnelRectangle
  DataAt tunnelRectangles{0x42A4};
  /// bit 0: inside the station's safe zone (UpdateSafeZone)
  DataField<std::uint8_t> safeZoneFlags{0x4308};
  /// shooter's +3C; bit 7 picks the aft shield
  DataField<std::uint8_t> playerHitByDepth{0x4309};
  /// 'Leaving Space Station'
  DataAt leavingStationMessage{0x430A};
  /// 'Auto-Dock Sequence Initiated'
  DataAt autoDockMessage{0x4320};
  /// 36 (0x24) from SetUpLocalSpace: object slots then debris slots
  DataField<std::uint8_t> shipSlotCount{0x433D};
  /// currentGovernment on arrival (0x2B56), 0 in witch space (0x2A51); spawn limits and the station handler use it
  DataField<std::uint8_t> spawnGovernment{0x433E};
  /// SpawnPlayerWreckage: the player's nose direction times 40 (ComputeDeathDebrisVector), x
  DataField<std::uint16_t> wreckDriftX{0x433F};
  /// as wreckDriftX, y
  DataField<std::uint16_t> wreckDriftY{0x4341};
  /// as wreckDriftX, z
  DataField<std::uint16_t> wreckDriftZ{0x4343};
  /// set when playerEnergy goes below 0 (DrainEnergy, ApplyEnemyLaserHit) or by KillPlayer; GameLoop then reruns the title
  DataField<std::uint8_t> playerDead{0x4345};
  /// 16-byte glyph; 8 rows of one word (8 pixels at 2 bpp), from character 0x20; DrawViewChar and DrawScreenChar; smallFont follows
  DataTable<16, 99> screenFont{0x4350};
  /// 10-byte glyph; 'A'-'Z', 5 rows of one word, a 6-pixel letter; DrawSmallViewChar
  DataTable<10, 26> smallFont{0x4980};
  /// pixel pattern behind each glyph in the graphics printer (3130: ink from BX where the glyph is set, this word where it is clear);...
  DataField<std::uint16_t> textPaperPattern{0x4A84};
  /// dword; 1,000,000,000 down to 1; FormatCredits
  DataTable<4, 10> decimalDivisors32{0x4A86};
  /// 3-byte; 1,000,000, 100,000, 10,000; only the unreached FormatDecimal7
  DataTable<3, 3> decimalDivisors24{0x4AB1};
  /// word; 10,000 down to 1; FormatDecimal5 stops at the 1
  DataTable<2, 5> decimalDivisors16{0x4ABA};
  /// only the unreached FormatCounter24
  DataBlock<7> counter24Text{0x4AC5};
  /// only the unreached AddToCounter24 and ResetCounter24
  DataBlock<3> counter24{0x4AD8};
  /// 'Front View', message-line default for viewAngle 0
  DataAt frontViewText{0x4ADB};
  /// 'Rear View', for 0x400
  DataAt rearViewText{0x4AE6};
  /// 'Left View', for 0x200
  DataAt leftViewText{0x4AF0};
  /// 'Right View', otherwise
  DataAt rightViewText{0x4AFA};
  /// pointer of the text on the message line now; UpdateMessageLine redraws only when messagePointer differs
  DataField<std::uint16_t> messageShown{0x4B05};
  /// text the message line should show; written with messageFrames by about 18 routines
  DataField<std::uint16_t> messagePointer{0x4B07};
  /// frames left; posters write it as a word, which also zeroes messageDrawn
  DataField<std::uint16_t> messageFrames{0x4B09};
  /// 0 = a new message is waiting; UpdateMessageLine sets 0xFF
  DataField<std::uint8_t> messageDrawn{0x4B0A};
  /// 'BOUNTY:000000 Cr'; ShowBountyMessage writes the digits at DS:4B12
  DataAt bountyText{0x4B0B};
  /// 'CLASS: 1234567 TYPE: 12345678901'; ShowShipIdentity fills the fields at DS:4B23 (7) and DS:4B31 (11)
  DataAt shipIdentityText{0x4B1C};
  /// 8-byte text; indexed by slot +0x33: None, Station, Attack, Debris, Trader, Wolf, Hunter, Debris, Simple, Hermit, Police
  DataTable<8, 11> shipClassNames{0x4B3D};
  /// 12-byte text; indexed by type: Dodo, Coriolis, Boa, Anaconda, Cobra MkI, Astroid, Boulder, Thargon, Shuttle, Transporter, Worm, S...
  DataTable<12, 32> shipTypeNames{0x4B95};
  /// code; CheckMissileWarning, CheckAltitudeWarning, CheckTemperatureWarning, CheckEnergyWarning; jmp [bx+0x4D15] at 0x36E3
  DataTable<2, 4> warningChecks{0x4D15};
  /// text of the active warning
  DataField<std::uint16_t> warningMessage{0x4D1D};
  /// 20 when a warning is raised; counts down
  DataField<std::uint8_t> warningFrames{0x4D1F};
  /// last warning raised; the next search starts after it
  DataField<std::uint8_t> warningIndex{0x4D20};
  /// pointer; DS:4D29 'INCOMING MISSILE!', 4D1B 'ALTITUDE LOW!', 4D29 'TEMPERATURE HIGH!', 4D3B 'ENERGY LOW!'
  DataTable<2, 4> warningTexts{0x4D21};
  /// the 30 blueprints back to back, DS:4D70-68C8, type 0 (the Dodo: 12 faces, 38 triangle items, face count at DS:4DCB) first; bluepr...
  DataBlock<7001> blueprints{0x4D70};
  /// type 1; 16 projected vertices, 28 face edges of which faces draw 0, 14 faces from DS:4F23 (count byte) with 22 triangle and 0 edg...
  DataBlock<288> coriolisBlueprint{0x4E94};
  /// type 2; 13 projected vertices, 24 face edges of which faces draw 0, 13 faces from DS:5035 (count byte) with 22 triangle and 0 edg...
  DataBlock<270> boaBlueprint{0x4FB4};
  /// type 3; 15 projected vertices, 25 face edges of which faces draw 0, 12 faces from DS:5169 (count byte) with 26 triangle and 0 edg...
  DataBlock<320> anacondaBlueprint{0x50C2};
  /// type 4; 11 projected vertices, 18 face edges of which faces draw 1, 10 faces from DS:5268 (count byte) with 14 triangle and 6 edg...
  DataBlock<205> cobraMk1Blueprint{0x5202};
  /// type 5; 9 projected vertices, 21 face edges of which faces draw 0, 14 faces from DS:532A (count byte) with 14 triangle and 0 edge...
  DataBlock<204> asteroidBlueprint{0x52CF};
  /// type 6; 7 projected vertices, 15 face edges of which faces draw 0, 10 faces from DS:53E4 (count byte) with 10 triangle and 0 edge...
  DataBlock<154> boulderBlueprint{0x539B};
  /// type 7; 12 projected vertices, 18 face edges of which faces draw 0, 8 faces from DS:5497 (count byte) with 20 triangle and 0 edge...
  DataBlock<211> thargonBlueprint{0x5435};
  /// type 8; 19 projected vertices, 30 face edges of which faces draw 11, 13 faces from DS:5597 (count byte) with 14 triangle and 12 e...
  DataBlock<264> shuttleBlueprint{0x5508};
  /// type 9; 37 projected vertices, 46 face edges of which faces draw 19, 14 faces from DS:5729 (count byte) with 28 triangle and 20 e...
  DataBlock<470> transporterBlueprint{0x5610};
  /// type 10; 10 projected vertices, 17 face edges of which faces draw 0, 8 faces from DS:5847 (count byte) with 16 triangle and 0 edg...
  DataBlock<194> wormBlueprint{0x57E6};
  /// type 11; 4 projected vertices, 6 face edges of which faces draw 0, 4 faces from DS:58CB (count byte) with 4 triangle and 0 edge i...
  DataBlock<68> splinterBlueprint{0x58A8};
  /// type 12; 4 projected vertices, 4 face edges of which faces draw 0, 2 faces from DS:590B (count byte) with 4 triangle and 0 edge i...
  DataBlock<56> plateBlueprint{0x58EC};
  /// type 13; 12 projected vertices, 17 face edges of which faces draw 2, 9 faces from DS:5993 (count byte) with 12 triangle and 2 edg...
  DataBlock<198> geckoBlueprint{0x5924};
  /// type 14; 14 projected vertices, 19 face edges of which faces draw 5, 9 faces from DS:5A5A (count byte) with 10 triangle and 5 edg...
  DataBlock<194> morayBlueprint{0x59EA};
  /// type 15; 18 projected vertices, 29 face edges of which faces draw 0, 13 faces from DS:5B43 (count byte) with 26 triangle and 0 ed...
  DataBlock<308> adderBlueprint{0x5AAC};
  /// type 16; 25 projected vertices, 28 face edges of which faces draw 16, 5 faces from DS:5CA3 (count byte) with 8 triangle and 16 ed...
  DataBlock<264> mambaBlueprint{0x5BE0};
  /// type 17; 10 projected vertices, 15 face edges of which faces draw 0, 7 faces from DS:5D35 (count byte) with 16 triangle and 0 edg...
  DataBlock<170> barrelBlueprint{0x5CE8};
  /// type 18; 16 projected vertices, 24 face edges of which faces draw 6, 10 faces from DS:5E16 (count byte) with 16 triangle and 6 ed...
  DataBlock<243> constrictorBlueprint{0x5D92};
  /// type 19; 19 projected vertices, 27 face edges of which faces draw 16, 8 faces from DS:5F20 (count byte) with 10 triangle and 24 e...
  DataBlock<252> cougarBlueprint{0x5E85};
  /// type 20; 17 projected vertices, 24 face edges of which faces draw 8, 9 faces from DS:5FFA (count byte) with 26 triangle and 12 ed...
  DataBlock<274> missileBlueprint{0x5F81};
  /// type 21; 4 projected vertices, 6 face edges of which faces draw 0, 4 faces from DS:60B2 (count byte) with 4 triangle and 0 edge i...
  DataBlock<64> escapePodBlueprint{0x6093};
  /// type 22; 20 projected vertices, 26 face edges of which faces draw 2, 10 faces from DS:616B (count byte) with 28 triangle and 2 ed...
  DataBlock<307> thargoidBlueprint{0x60D3};
  /// type 23; 19 projected vertices, 27 face edges of which faces draw 3, 11 faces from DS:6299 (count byte) with 18 triangle and 3 ed...
  DataBlock<267> ferDeLanceBlueprint{0x6206};
  /// type 24; 19 projected vertices, 28 face edges of which faces draw 5, 12 faces from DS:63AA (count byte) with 22 triangle and 8 ed...
  DataBlock<298> aspBlueprint{0x6311};
  /// type 25; 10 projected vertices, 15 face edges of which faces draw 0, 7 faces from DS:6486 (count byte) with 10 triangle and 0 edg...
  DataBlock<144> sidewinderBlueprint{0x643B};
  /// type 26; 28 projected vertices, 40 face edges of which faces draw 15, 13 faces from DS:65B9 (count byte) with 20 triangle and 18...
  DataBlock<389> cobraMk3Blueprint{0x64CB};
  /// type 27; 17 projected vertices, 21 face edges of which faces draw 4, 6 faces from DS:66C0 (count byte) with 10 triangle and 8 edg...
  DataBlock<185> kraitBlueprint{0x6650};
  /// type 28; 15 projected vertices, 20 face edges of which faces draw 6, 7 faces from DS:6771 (count byte) with 14 triangle and 6 edg...
  DataBlock<195> viperBlueprint{0x6709};
  /// type 29; 11 projected vertices, 26 face edges of which faces draw 0, 17 faces from DS:683C (count byte) with 18 triangle and 0 ed...
  DataBlock<253> pythonBlueprint{0x67CC};
  /// pointer; blueprint per ship type, indexed by byte0 & 0x3E (add bx,0x68C9 at 0x3E54); 0x4D70 for type 0, then 1-29 in order. The 3...
  DataTable<2, 30> blueprintTable{0x68C9};
  /// 36 64-byte records: slot 0 sun, 1 planet (planetSlot), 2 station (stationSlot), 3-19 ships (firstShipSlot), 20-35 debris (debrisS...
  DataAt shipSlots{0x6930};
  /// slot 1: type 0x1F set up by SetUpLocalSpace; compass target when far
  DataBlock<64> planetSlot{0x6970};
  /// slot 2: Coriolis or Dodo (SetUpLocalSpace, by DS:75BA < 9); also holds the compass dot (+0x26..+0x28) and target position (+0x20....
  DataBlock<64> stationSlot{0x69B0};
  /// slot 3; ship scans run objectSlotCount-3 slots from here
  DataAt firstShipSlot{0x69F0};
  /// slots 20-35, debrisSlotCount of them; FindDebrisSlot reuses the oldest (+0x2F); never get scanner blips
  DataBlock<1024> debrisSlots{0x6E30};
  /// 6-byte x,y,z words; model vertices 0-41 in view space; ProjectVertices projects the first projectedVertexCount in place into 4-by...
  DataTable<6, 42> vertexBuffer{0x7230};
  /// vertices 34-41 inside vertexBuffer, written by BuildBoxCornerVertices
  DataBlock<48> boxCornerVertices{0x72FC};
  /// DrawVisibleFaces keeps p1.x here (0x3ACB, 0x3B51) while BX indexes the vertices
  DataField<std::uint16_t> faceTestScratch{0x7330};
  /// byte; about sqrt(n) rounded, n=0-128 (n=57 and 73 hold 7 and 8); UpdateCompass reads n=65-98. Sits just past the 42 vertices, so...
  DataTable<1, 129> sqrtTable{0x7332};
  /// byte; 0x80, 0x20, 0x08, 0x02: a colour-2 pixel at each position in a CGA byte; XorDashboardPixel
  DataTable<1, 4> dashboardPixelMasks{0x73B3};
  /// written by RenderBlueprintBody (0x3D08); nothing reads it in ELITES and every blueprint's fixed-edge count is 0
  DataField<std::uint16_t> fixedEdgeList{0x73B7};
  /// written at 0x3D01, never read
  DataField<std::uint16_t> fixedEdgeCount{0x73B9};
  /// written at 0x3D17; read by DrawVisibleFaces (0x3AF7): 2-byte edges, byte0 = vertexA*4 (its low 2 bits always 0, masked off), byte...
  DataField<std::uint16_t> faceEdgeList{0x73BB};
  /// written at 0x3D10, never read
  DataField<std::uint16_t> faceEdgeCount{0x73BD};
  /// read by ProjectVertices
  DataField<std::uint16_t> projectedVertexCount{0x73BF};
  /// blueprint byte +2 (RunBlueprintHandler); 15 to 200; BuildDodoVertices ignores it
  DataField<std::uint16_t> boxHalfWidth{0x73C1};
  /// orientation angle, 800h per turn; with playerYawAngle sets the velocity direction (UpdatePlayerVelocity); re-derived after each p...
  DataField<std::uint16_t> playerPitchAngle{0x73C9};
  /// orientation angle, 800h per turn; see playerPitchAngle
  DataField<std::uint16_t> playerYawAngle{0x73CB};
  /// 800h per turn; the roll input is added to it directly; the docking computer matches it to the station's spin
  DataField<std::uint16_t> playerRollAngle{0x73CD};
  /// object +0x0A for the blueprint handler (0x3E5A)
  DataField<std::uint16_t> drawPitchAngle{0x73CF};
  /// object +0x0C
  DataField<std::uint16_t> drawYawAngle{0x73D1};
  /// object +0x0E
  DataField<std::uint16_t> drawRollAngle{0x73D3};
  /// slots before the debris: 20 (SetUpLocalSpace), 1 in the file
  DataField<std::uint8_t> objectSlotCount{0x73D5};
  /// 16
  DataField<std::uint8_t> debrisSlotCount{0x73D6};
  /// 100 in the file (ELITEL.EXE 10): ClassifyViewPosition does not draw an object whose view-space centre z is below it (0x3CA5)
  DataField<std::uint16_t> nearClipZ{0x73D7};
  /// 12000: CheckShipInRange
  DataField<std::uint16_t> maxAxisDistance{0x73D9};
  /// 2197 = 12000^2 >> 16: CheckShipInRange
  DataField<std::uint16_t> maxDistanceSquaredHigh{0x73DB};
  /// view-space centre of the object being drawn; ReflectVertexAboutCenter and OffsetVertexByCenter
  DataField<std::uint16_t> drawCenterX{0x73DD};
  DataField<std::uint16_t> drawCenterY{0x73DF};
  DataField<std::uint16_t> drawCenterZ{0x73E1};
  /// RotatePitchYawRoll and RotateBySinCos7210
  DataField<std::uint16_t> rotateScratch{0x73E3};
  /// 'SCOOP RETRIEVAL INACTIVE'
  DataAt scoopRetrievalInactiveText{0x73E5};
  /// 'cargo item...', overwritten by the scooped product's name
  DataBlock<14> scoopedCargoText{0x73FE};
  /// 'FUEL SCOOPS ACTIVE'
  DataAt fuelScoopsActiveText{0x740C};
  /// 'CARGO BAY FULL SCOOPS INACTIVE'
  DataAt cargoBayFullText{0x741F};
  /// 'Escape Pod Retrieved...Slaves!'
  DataAt escapePodRetrievedText{0x7440};
  /// 'Precious Gems and Metals'
  DataAt preciousMetalsText{0x745F};
  /// 'Metal Alloys'
  DataAt metalAlloysText{0x7478};
  /// TryScoopObject
  DataField<std::uint8_t> freeCargoTonnes{0x7485};
  /// 'Alien Items'
  DataAt alienItemsText{0x749D};
  /// 'Masking Device!'
  DataAt maskingDeviceText{0x74A9};
  /// word; low byte fills even buffer rows, high byte odd rows; read only at 0x3B34 (mov ax,[bx+0x74B9], BX=item byte & 0x7F, always e...
  DataTable<2, 16> faceFillPatterns{0x74B9};
  /// UpdateCompass; TransformAndDrawObjects classifies the station only when 1
  DataField<std::uint8_t> compassTargetIsStation{0x74D9};
  /// 'Hyperspaced into System!'
  DataBlock<25> arrivalSystemText{0x74E0};
  /// 'Hyperspace Motors Engaged'
  DataBlock<26> hyperspaceEngagedText{0x74F9};
  /// 'Hyperspaced into galaxy ' and a digit at DS:752B
  DataBlock<26> arrivalGalaxyText{0x7513};
  /// galaxyNumber + '1', written by GalacticJump into arrivalGalaxyText
  DataBlock<1> arrivalGalaxyDigit{0x752B};
  /// 'Welcome to the 9th Galaxy!'
  DataBlock<27> ninthGalaxyText{0x752D};
  /// 'Hyperspaced into WITCH SPACE!'; never selected (see 0x4807)
  DataBlock<30> witchSpaceArrivalText{0x7548};
  /// selectedDistanceTenthsLy*36/10 (at least 1), set when H starts the countdown; taken from fuel on arrival (4720)
  DataField<std::uint8_t> hyperspaceFuelCost{0x7566};
  /// 208: length of commanderBlock, the size read and written at 0x0340 and 0x036D
  DataField<std::uint16_t> commanderFileBytes{0x7567};
  /// 25 in the file; length of a system record copy
  DataField<std::uint16_t> systemRecordBytes{0x7569};
  /// the commander file image (int 21h AH=3Fh/40h from here)
  DataBlock<208> commanderBlock{0x756B};
  /// frame bytes 0x0F 0x0D then "COMMANDER " (ShowCommanderStatusScreen)
  DataAt commanderTitle{0x757A};
  /// 'COMMANDER', the rank inside commanderTitle (DS:757A, frame bytes first); AwardArchangelTitle overwrites it
  DataBlock<9> commanderRankText{0x757C};
  /// cash as text, " 100.0 Credits", written by FormatCredits
  DataBlock<19> creditBalanceText{0x7587};
  /// with randomState1-2 three words stepped by NextRandom (a,b,c -> b,c,c+a+b); ShowBuyCargoScreen copies all three to marketRandomState
  DataField<std::uint16_t> randomState0{0x759B};
  DataField<std::uint16_t> randomState1{0x759D};
  DataField<std::uint16_t> randomState2{0x759F};
  /// 0-7, index into galaxySeeds
  DataField<std::uint8_t> galaxyNumber{0x75A1};
  /// 0x14 (Lave) in the file
  DataField<std::uint8_t> currentSystemX{0x75A2};
  /// the current system's y/2; 0x56 (Lave) in the file
  DataField<std::uint8_t> currentSystemChartY{0x75A3};
  DataField<std::uint8_t> chartCursorX{0x75A4};
  /// 0-0x7F
  DataField<std::uint8_t> chartCursorY{0x75A5};
  /// the short-range chart's cursor kept between visits
  DataField<std::uint8_t> shortRangeCursorX{0x75A6};
  DataField<std::uint8_t> shortRangeCursorY{0x75A7};
  /// the galactic chart's cursor kept between visits
  DataField<std::uint8_t> galacticCursorX{0x75A8};
  DataField<std::uint8_t> galacticCursorY{0x75A9};
  /// 0 galactic chart, 1 short-range
  DataField<std::uint8_t> chartIsShortRange{0x75AA};
  /// start of the current system's 25-byte record DS:75AB-71F3, laid out like the selected one from DS:75C4: name (9), name length (+9...
  DataBlock<9> currentSystemName{0x75AB};
  /// 7 (Lave) in the file; DS:75AB-71F3 is the current system's record, laid out as the selected one at DS:75C4
  DataField<std::uint8_t> currentSystemIndex{0x75B5};
  /// 0-7, names DS:7CBD; equipment and market prices, ship spawn tables (0x4A86)
  DataField<std::uint8_t> currentGovernment{0x75B8};
  /// 0-7, names DS:7C0C; equipment and market prices
  DataField<std::uint8_t> currentEconomy{0x75B9};
  /// 0-based; equipment for sale has tech byte < this+2; market prices use min(this,9); 9+ makes the station a Dodo (0x2ADE)
  DataField<std::uint8_t> currentTechLevel{0x75BA};
  DataField<std::uint8_t> data75BC{0x75BC};
  DataField<std::uint8_t> data75BF{0x75BF};
  /// start of the selected (hyperspace target) system's record, filled by SelectSystemAtCursor and rebuilt at every WaitForScreenExitK...
  DataBlock<8> selectedSystemName{0x75C4};
  /// characters 5-6 of selectedSystemName; GenerateSystemName blanks them
  DataField<std::uint16_t> data75C8{0x75C8};
  /// characters 7-8 of selectedSystemName; GenerateSystemName blanks them
  DataField<std::uint16_t> data75CA{0x75CA};
  /// written by GenerateSystemName; TerminateSelectedSystemName puts the NUL here
  DataField<std::uint8_t> selectedSystemNameLength{0x75CD};
  /// 0-255 in the galaxy
  DataField<std::uint8_t> selectedSystemIndex{0x75CE};
  /// printed as nnn.n Light Years; 0 = none selected (No System Selected), 47h or more = out of range; compared with fuel*10/36 by H
  DataField<std::uint16_t> selectedDistanceTenthsLy{0x75CF};
  /// index into DS:7CBD names (Anarchy ... Corporate State)
  DataField<std::uint8_t> selectedGovernment{0x75D1};
  /// index into DS:7C0C names (Poor Agricultural ... Rich Industrial)
  DataField<std::uint8_t> selectedEconomy{0x75D2};
  /// shown +1
  DataField<std::uint8_t> selectedTechLevel{0x75D3};
  /// tenths of a billion
  DataField<std::uint8_t> selectedPopulationTenthsBillion{0x75D4};
  /// 0xFF = Human Colonials; otherwise size adjective index (DS:7D9E)
  DataField<std::uint8_t> selectedSpeciesAdjective1{0x75D5};
  /// index into DS:7DC5
  DataField<std::uint8_t> selectedSpeciesAdjective2{0x75D6};
  /// index into DS:7E01
  DataField<std::uint8_t> selectedSpeciesAdjective3{0x75D7};
  /// index into DS:7E3D (Rodents ... Insects)
  DataField<std::uint8_t> selectedSpeciesType{0x75D8};
  /// millions of credits
  DataField<std::uint16_t> selectedProductivityMillionCredits{0x75D9};
  /// shown in km
  DataField<std::uint16_t> selectedRadiusKm{0x75DB};
  /// with descriptionSeed1 (DS:75DF) stepped by NextDescriptionRandom; set by SelectSystemAtCursor (0x1284)
  DataField<std::uint16_t> descriptionSeed0{0x75DD};
  /// descriptionSeed0 XOR systemSeed2
  DataField<std::uint16_t> descriptionSeed1{0x75DF};
  /// 255 = full; light years = value/36 (255 shows 7.0); equipment item 1
  DataField<std::uint8_t> fuel{0x75E2};
  /// equipment item 2, at most 4
  DataField<std::uint8_t> missileCount{0x75E3};
  /// item 3; hold 35 t instead of 20
  DataField<std::uint8_t> largeCargoBayFitted{0x75E4};
  /// item 4 (by the order of DS:7EC4 and DS:84D2)
  DataField<std::uint8_t> ecmFitted{0x75E5};
  /// item 5; one per mount fitted
  DataField<std::uint8_t> pulseLaserCount{0x75E6};
  /// item 6
  DataField<std::uint8_t> beamLaserCount{0x75E7};
  /// item 7; needed before mining lasers
  DataField<std::uint8_t> fuelScoopsFitted{0x75E8};
  /// item 8
  DataField<std::uint8_t> escapePodFitted{0x75E9};
  /// item 9
  DataField<std::uint8_t> energyBombFitted{0x75EA};
  /// item 10
  DataField<std::uint8_t> energyUnitFitted{0x75EB};
  /// item 11
  DataField<std::uint8_t> dockingComputerFitted{0x75EC};
  /// item 12; cleared at 0x4802
  DataField<std::uint8_t> galacticHyperdriveFitted{0x75ED};
  /// item 13; one more rock may spawn while it is 1 (0x4AB2)
  DataField<std::uint8_t> miningLaserCount{0x75EE};
  /// item 14
  DataField<std::uint8_t> militaryLaserCount{0x75EF};
  /// mission 2 reward, 'N' in flight (0x836F)
  DataField<std::uint8_t> maskingDeviceFitted{0x75F0};
  /// bits 0-3: fore, aft, right, left hold a laser
  DataField<std::uint8_t> laserMountsFitted{0x75F1};
  /// 2 bits per mount, mount 0 lowest: 0 pulse, 1 beam, 2 mining, 3 military
  DataField<std::uint8_t> laserMountTypes{0x75F2};
  /// 32-bit cash in tenths of a credit, low word first
  DataBlock<4> creditsTenths{0x75F3};
  DataField<std::uint16_t> data75F5{0x75F5};
  /// 0 clean, 1-39 offender, 40+ fugitive (DS:842A); saturates at 255; -5 per jump (0x4727)
  DataField<std::uint8_t> legalStatus{0x75F7};
  /// incremented by CreditKill for kills with a bounty, saturates at 254; rating = first DS:8457 threshold above it; enemy missiles ne...
  DataField<std::uint8_t> killCount{0x75F8};
  /// JAMESON
  DataAt defaultCommanderName{0x75F9};
  /// byte pair; per commodity: units held, units on sale here; entry 17 is refugeesTonnes/cargoUsedTonnes
  DataTable<2, 18> cargoHold{0x7602};
  /// product 3; escape pods
  DataField<std::uint8_t> cargoSlavesTonnes{0x7608};
  /// product 9
  DataField<std::uint8_t> cargoAlloysTonnes{0x7614};
  /// product 12
  DataField<std::uint8_t> cargoMineralsTonnes{0x761A};
  /// product 13; capped at 0xFA when scooped
  DataField<std::uint8_t> cargoGoldKg{0x761C};
  /// product 14
  DataField<std::uint8_t> cargoPlatinumKg{0x761E};
  /// product 15
  DataField<std::uint8_t> cargoGemStonesGrams{0x7620};
  /// product 16; Thargons
  DataField<std::uint8_t> cargoAlienItemsTonnes{0x7622};
  /// mission 1 refugees aboard (20 or 35), shown as "Refugees" by ShowInventoryScreen
  DataField<std::uint8_t> refugeesTonnes{0x7624};
  /// tonnes in the hold (gold, platinum and gems excluded); capacity 20, 35 with the extension
  DataField<std::uint8_t> cargoUsedTonnes{0x7625};
  /// 0 after an arrival (0x4754); ShowBuyCargoScreen then rolls the quantities on sale and sets 1
  DataField<std::uint8_t> marketQuantitiesSet{0x7626};
  /// jumps counted by UpdateMissionSchedule
  DataField<std::uint8_t> missionJumpCount{0x7627};
  /// 0 none, 1 supernova refugees, 2 masking device, 3 Thargoid invasion; set at 0x499B, cleared by ShowMissionDebriefing
  DataField<std::uint8_t> missionNumber{0x7628};
  DataField<std::uint8_t> data7629{0x7629};
  /// nonzero in witch space: 100 on entry (0x4917), lowered by Thargoid kills (0x8C03); the status screen shows WITCH SPACE
  DataField<std::uint8_t> witchspaceCountdown{0x762A};
  /// frames before a fuel leak starts; 50 set on arrival in missions 1 and 3
  DataField<std::uint8_t> fuelLeakDelayFrames{0x762B};
  /// 51 when a leak starts; frames of leak left
  DataField<std::uint8_t> fuelLeakFrames{0x762C};
  /// set when the ship carrying the masking device is destroyed
  DataField<std::uint8_t> maskShipDestroyed{0x762D};
  /// set by TryScoopObject (0x447A); mission 2 debrief fits the cloaking device
  DataField<std::uint8_t> maskingDeviceRecovered{0x762E};
  /// 5 at the mission 2 briefing; decremented by TallyMaskMissionKill; mask spawning runs while nonzero
  DataField<std::uint8_t> maskMissionShipsLeft{0x762F};
  /// mission 3: set by ShowMissionBriefing; ships may fire in the safe zone, docking is refused (0x2C32), missiles damage the station;...
  DataField<std::uint8_t> thargoidInvasionActive{0x7630};
  /// set at 0x5589 and 0x8B46
  DataField<std::uint8_t> invadedStationDestroyed{0x7631};
  /// mission 3 reward, 'L' in flight (0x8385) toggles DS:AC0E
  DataField<std::uint8_t> antiEcmEmulatorFitted{0x7632};
  /// 0 until supernovaFrames runs out; then starts from cabinTemperature and grows by max(1, h/4) a frame, killing on overflow (0x3F68...
  DataField<std::uint8_t> supernovaHeat{0x7633};
  /// 400 after the supernova briefing (0x6E77); counts down at 0x3F5E and stays 1; cleared on arrival
  DataField<std::uint16_t> supernovaFrames{0x7634};
  /// 0 not briefed, 1 briefed, 2 debriefing on screen
  DataField<std::uint8_t> missionStage{0x7636};
  /// set on every hyperspace arrival (0x47E1), cleared at a briefing; mission 1 completes only after a jump
  DataField<std::uint8_t> jumpedSinceBriefing{0x7637};
  /// set at 0x4968; mission 2 debrief "Running away from the mask ship..."
  DataField<std::uint8_t> fledMaskShip{0x7638};
  /// 2 at the mission 2 briefing; -1 per arrival; 1 means the mask ship's system
  DataField<std::uint8_t> maskSystemJumps{0x7639};
  /// selectedSystemIndex latched when the countdown starts
  DataField<std::uint8_t> hyperspaceTargetIndex{0x763A};
  /// copy of commanderBlock taken by SaveStartupCommander
  DataBlock<208> startupCommander{0x763C};
  /// 3 bytes; delay frames, radius, colour per ring; copied to hyperspaceRings by ResetHyperspaceRings
  DataTable<3, 10> hyperspaceRingStart{0x783C};
  /// 3 bytes; working copy animated by DrawHyperspaceRings
  DataTable<3, 10> hyperspaceRings{0x785A};
  /// 'FUEL LEAK!'
  DataBlock<11> fuelLeakText{0x7878};
  /// 'ARCHANGEL', ended by the forceMisjump byte
  DataBlock<9> archangelTitle{0x7883};
  /// set by ReadScanCode when W (11h) is pressed while Alt is held; on hyperspace arrival (478C) it forces EnterWitchSpace, which puts...
  DataField<std::uint8_t> forceMisjump{0x788C};
  /// selectedSystemName latched when the countdown starts
  DataBlock<25> hyperspaceTargetRecord{0x788D};
  /// code; call [bx+0x7990] at 0x4A41, index byte +33: SkipInertObjectAi, UpdateStationAi, UpdateMissileAi, UpdateDriftingObjectAi, Up...
  DataTable<2, 8> behaviorHandlers{0x7990};
  /// active objects of class other than 7 this frame; spawning needs < 10
  DataField<std::uint8_t> activeObjectCount{0x79A0};
  /// byte; active objects per class 0-7, recounted each frame by UpdateObjectsAndSpawn
  DataTable<1, 8> behaviorClassCounts{0x79A1};
  /// behaviorClassCounts[3]: class 3 ('Debris'/'Simple' drifters)
  DataField<std::uint8_t> drifterCount{0x79A4};
  /// behaviorClassCounts[4]: class 4 ('Trader')
  DataField<std::uint8_t> traderCount{0x79A5};
  /// behaviorClassCounts[5]: class 5 ('Wolf'); also gates mask and invasion spawns
  DataField<std::uint8_t> wolfCount{0x79A6};
  /// behaviorClassCounts[6]: class 6 ('Hunter')
  DataField<std::uint8_t> hunterCount{0x79A7};
  /// 10-byte record; type, speed, turn rate, bounty, missiles, cargo, fragments, energy, +3F, range high byte; read by InitObjectFromT...
  DataTable<10, 31> spawnTemplates{0x79A9};
  /// 4 bytes; max objects of class 3, 4, 6, 5, indexed by spawnGovernment x 4
  DataTable<4, 8> spawnLimitsByGovernment{0x7ADF};
  /// column of spawnLimitsByGovernment: max class 4
  DataField<std::uint8_t> traderLimitColumn{0x7AE0};
  /// column of spawnLimitsByGovernment: max class 6
  DataField<std::uint8_t> hunterLimitColumn{0x7AE1};
  /// column of spawnLimitsByGovernment: max class 5
  DataField<std::uint8_t> wolfLimitColumn{0x7AE2};
  /// spawnGovernment x 4, set by UpdateObjectsAndSpawn
  DataField<std::uint16_t> spawnLimitOffset{0x7AFF};
  /// NPC ECM: 20 from the station or a fleeing trader, 30 from a Thargoid; counted down only by UpdateStationAi, which removes all mis...
  DataField<std::uint8_t> npcEcmFrames{0x7B01};
  /// set by UpdateMissileAi; CheckMissileWarning clears it
  DataField<std::uint8_t> incomingMissileAlert{0x7B02};
  /// mask ship slot kept while its escorts are placed
  DataField<std::uint16_t> maskShipSlot{0x7B03};
  /// 1 while ExplodeObject explodes a station: 10 extra debris steps
  DataField<std::uint8_t> explodingStation{0x7B06};
  /// currentGovernment x 8, set by UpdateObjectsAndSpawn
  DataField<std::uint16_t> spawnOddsOffset{0x7B07};
  /// 4 words; spawn chance per frame out of 65536 for class 3, 4, 6, 5, indexed by currentGovernment x 8
  DataTable<8, 8> spawnOddsByGovernment{0x7B09};
  /// column of spawnOddsByGovernment: class 4
  DataField<std::uint16_t> traderOddsColumn{0x7B0B};
  /// column of spawnOddsByGovernment: class 6
  DataField<std::uint16_t> hunterOddsColumn{0x7B0D};
  /// column of spawnOddsByGovernment: class 5
  DataField<std::uint16_t> wolfOddsColumn{0x7B0F};
  /// Release:1? 1-10-87
  DataAt versionString{0x7B50};
  /// frame bytes, then "SELL CARGO"
  DataAt sellCargoFrame{0x7B63};
  /// frame bytes, then "BUY CARGO"
  DataAt buyCargoFrame{0x7B70};
  /// frame bytes, then "EQUIP SHIP"
  DataAt equipShipFrame{0x7B7C};
  /// frame bytes, then "DATA ON "
  DataAt systemDataFrame{0x7B89};
  /// frame bytes, then " MARKET PRICES"
  DataAt marketPricesFrame{0x7B94};
  /// frame bytes, then "DISC/CONTROL"
  DataAt discControlFrame{0x7BA5};
  /// frame bytes, then "INVENTORY"
  DataAt inventoryFrame{0x7BB4};
  /// frame bytes, then "EMERGENCY"
  DataAt emergencyFrame{0x7BC0};
  /// pointer; Poor Agricultural ... Rich Industrial
  DataTable<2, 8> economyNames{0x7C0C};
  /// pointer; Anarchy ... Corporate State
  DataTable<2, 8> governmentNames{0x7CBD};
  DataField<std::uint8_t> data7D48{0x7D48};
  DataField<std::uint8_t> data7D49{0x7D49};
  /// pointer; indexed by selectedSpeciesAdjective1: Large, Fierce, Small, then empty
  DataTable<2, 8> speciesSizeNames{0x7D9E};
  /// pointer; indexed by selectedSpeciesAdjective2: Green, Red, Yellow, Blue, Black, Harmless, empty
  DataTable<2, 8> speciesColorNames{0x7DC5};
  /// pointer; indexed by selectedSpeciesAdjective3: Slimy, Bug-Eyed, Horned, Bony, Fat, Furry, empty
  DataTable<2, 8> speciesTraitNames{0x7E01};
  /// pointer; indexed by selectedSpeciesType: Rodents) ... Insects)
  DataTable<2, 8> speciesTypeNames{0x7E3D};
  DataField<std::uint8_t> data7EA3{0x7EA3};
  DataField<std::uint8_t> data7EBB{0x7EBB};
  /// record; count byte, then per item: tech byte, NUL-terminated name, govFactor, econFactor (signed bytes), base price word in tenth...
  DataAt equipmentList{0x7EC4};
  /// FormatTenths output, "nnnn.n"
  DataBlock<7> priceText{0x803C};
  DataField<std::uint8_t> data8040{0x8040};
  DataField<std::uint8_t> data8041{0x8041};
  /// count byte (6), then the Equip Ship help lines and column header
  DataAt equipHelpText{0x8043};
  /// pointer; Pulse, Beam, Mining, Military
  DataTable<2, 4> laserTypeNames{0x81BA};
  /// pointer; Fore, "Aft," "Right," "Left,"
  DataTable<2, 4> laserMountNames{0x81F4};
  /// the price ComputeResalePrice reads
  DataField<std::uint16_t> resalePriceInput{0x8219};
  /// rows in the current cursor menu (17 for cargo, the listed equipment)
  DataField<std::uint8_t> menuRowCount{0x822A};
  /// text-memory address of the first row's first attribute byte
  DataField<std::uint16_t> menuFirstRowAttr{0x822B};
  /// 1-based; also the item index SelectLaserType tests
  DataField<std::uint8_t> menuSelectedRow{0x822D};
  /// 0 fore, 1 aft, 2 right, 3 left
  DataField<std::uint8_t> selectedLaserMount{0x822E};
  /// word pair; cargo rows from 0: buy price, sell price; equipment rows from index 1: price, resale price; tenths of credits
  DataTable<4, 17> screenPrices{0x823B};
  DataField<std::uint16_t> data823F{0x823F};
  DataField<std::uint16_t> data8245{0x8245};
  DataField<std::uint8_t> data83F7{0x83F7};
  DataField<std::uint8_t> data83F9{0x83F9};
  DataField<std::uint8_t> data840A{0x840A};
  DataField<std::uint8_t> data840B{0x840B};
  /// pointer; Clean, Offender, Fugitive
  DataTable<2, 3> legalStatusNames{0x842A};
  /// byte; 2, 4, 9, 20, 35, 90, 155, 230, 255 against killCount
  DataTable<1, 9> ratingThresholds{0x8457};
  /// pointer; Harmless ... Elite
  DataTable<2, 9> ratingNames{0x8460};
  /// pointer; status-screen names for DS:75E3..75EF
  DataTable<2, 13> equipmentNames{0x84D2};
  DataField<std::uint8_t> data84F5{0x84F5};
  /// count byte (6), then the Disc/Control menu lines
  DataAt discMenuText{0x85A9};
  /// pointer; indexed by inputDevice: Keyboard, Joystick, Mouse; ShowControlDevice prints it
  DataTable<2, 3> inputDeviceNames{0x8670};
  /// '12345678.CDR' template; load, save and delete use it
  DataBlock<13> commanderFileName{0x868A};
  /// pointer; LOADED:, SAVED:, DELETED:, CATALOGUED, by diskOperation 1-4
  DataTable<2, 4> diskOperationNames{0x86D9};
  /// 1 after Esc, J, A: the Amstrad joystick, whose moves arrive as scan codes 0x77-0x7C; ReadSteering tests it at 0x7607
  DataField<std::uint8_t> joystickIsAmstrad{0x8836};
  /// 0 keyboard, 1 joystick, 2 mouse (names DS:8670)
  DataField<std::uint8_t> inputDevice{0x8837};
  /// set when a scan code 0x77-0x7C arrives during Amstrad joystick detection
  DataField<std::uint8_t> amstradJoystickMoved{0x884D};
  /// text; 17-byte rows: name, unit (t, kg, g); the 18th is Refugees
  DataAt productNames{0x8863};
  /// word; [commodity*16 + economy*2], factor/256
  DataTable<2, 136> economyPriceFactors{0x899B};
  /// word; [commodity*16 + government*2], factor/256
  DataTable<2, 136> governmentPriceFactors{0x8AAB};
  /// word
  DataTable<2, 17> productBasePrices{0x8BBB};
  /// 3 bytes; price adjust, tech-level factor (both 0 in the file), legal penalty on sale (1 for slaves, narcotics, firearms)
  DataTable<3, 17> productTradeRecords{0x8BDD};
  DataField<std::uint8_t> data8BDF{0x8BDF};
  DataField<std::uint16_t> data8C10{0x8C10};
  DataField<std::uint16_t> data8C12{0x8C12};
  DataField<std::uint16_t> data8C14{0x8C14};
  /// walks cargoHold while the trade screens draw
  DataField<std::uint16_t> cargoRowPointer{0x8C16};
  /// number text for the trade screens and the typed quantity
  DataBlock<6> quantityText{0x8C18};
  /// copy of randomState0 stepped by NextMarketRandom
  DataBlock<6> marketRandomState{0x8C1E};
  DataField<std::uint16_t> data8C20{0x8C20};
  DataField<std::uint16_t> data8C22{0x8C22};
  /// 0 sell screen (F2), 1 buy screen (F3); RunCargoTradeMenu ignores the screen's own F-key (0x3C+this), B on the sell screen and S o...
  DataField<std::uint8_t> tradeScreenIsBuy{0x8C24};
  /// 0 pulse, 1 beam, 2 mining, 3 military
  DataField<std::uint8_t> selectedLaserType{0x8E2E};
  /// currentTechLevel clamped to 9
  DataField<std::uint8_t> marketTechLevel{0x8E2F};
  /// 5 lines ending "Will you help us (Y/N)?"
  DataAt supernovaBriefingText{0x8E3C};
  /// frame bytes, then "TASK COMPLETE - CONGRATULATIONS!"
  DataAt taskCompleteFrame{0x9033};
  /// '0' or '4' patched into "Please accept 1000 Credits!"
  DataField<std::uint8_t> refugeeRewardDigit{0x907E};
  /// 9 lines on the invisible masking device
  DataAt maskBriefingText{0x90A8};
  /// 12 lines on the Thargoid-invaded system
  DataAt invasionBriefingText{0x9381};
  /// 14 lines: anti-ECM device on 'L', title Archangel
  DataAt invasionDebriefText{0x94B9};
  /// control codes 5 and 6
  DataField<std::uint8_t> descriptionCapitalize{0x9659};
  /// code 6, phrase 0x92, "is ", phrase 0x93, code 4, "."
  DataAt descriptionTemplate{0x965A};
  /// expanded description
  DataBlock<256> descriptionBuffer{0x9663};
  /// code; jmp [bx] at 0x7029 for codes 1-6: InsertSystemName, InsertSystemAdjective, InsertRandomName, BackspaceDescription, StartCap...
  DataTable<2, 6> textControlCodes{0x9763};
  /// pointer; for bytes 0x80-0xA6; each points at 5 string pointers. Follows textControlCodes' 6 code entries
  DataTable<2, 39> descriptionPhraseLists{0x976F};
  /// system or random name for codes 1-3
  DataBlock<13> descriptionNameBuffer{0xA017};
  /// ian
  DataBlock<5> adjectiveSuffix{0xA024};
  /// 1 while the key is held, indexed by the scan code itself (entry 0 unused; the map's 'scan code - 1' misses the inc ah at 7452); w...
  DataBlock<128> keyDown{0xA030};
  /// keyDown entry for scan code 01h: pauses the game in flight (ProcessFlightKeys 813D)
  DataField<std::uint8_t> keyDownEsc{0xA031};
  /// keyDown entry for scan code 10h: pitch -1 (ReadKeyboardSteering)
  DataField<std::uint8_t> keyDownQ{0xA040};
  /// keyDown entry for scan code 12h: ECM (ProcessFlightKeys 829F)
  DataField<std::uint8_t> keyDownE{0xA042};
  /// keyDown entry for scan code 14h: primes a missile (8171)
  DataField<std::uint8_t> keyDownT{0xA044};
  /// keyDown entry for scan code 16h: unarms the missile (81FB)
  DataField<std::uint8_t> keyDownU{0xA046};
  /// keyDown entry for scan code 17h: ID indicator: identifies the ship in the sights (82FE)
  DataField<std::uint8_t> keyDownI{0xA047};
  /// keyDown entry for scan code 18h: roll -1 (ReadKeyboardSteering)
  DataField<std::uint8_t> keyDownO{0xA048};
  /// keyDown entry for scan code 19h: roll +1 (ReadKeyboardSteering)
  DataField<std::uint8_t> keyDownP{0xA049};
  /// keyDown entry for scan code 1Dh: with Esc, a freeze without the pause menu (8149)
  DataField<std::uint8_t> keyDownCtrl{0xA04D};
  /// keyDown entry for scan code 1Eh: pitch +1 (ReadKeyboardSteering)
  DataField<std::uint8_t> keyDownA{0xA04E};
  /// keyDown entry for scan code 22h: arms the galactic hyperdrive (802E)
  DataField<std::uint8_t> keyDownG{0xA052};
  /// keyDown entry for scan code 23h: hyperspace (805E)
  DataField<std::uint8_t> keyDownH{0xA053};
  /// keyDown entry for scan code 24h: jump drive (8133)
  DataField<std::uint8_t> keyDownJ{0xA054};
  /// keyDown entry for scan code 26h: anti-ECM emulator while held (837E)
  DataField<std::uint8_t> keyDownL{0xA056};
  /// keyDown entry for scan code 2Ah: makes ReadScanCode OR 80h into the buffered code
  DataField<std::uint8_t> keyDownLeftShift{0xA05A};
  /// keyDown entry for scan code 2Eh: launches the escape capsule (82DC)
  DataField<std::uint8_t> keyDownC{0xA05E};
  /// keyDown entry for scan code 30h: energy bomb (82C6)
  DataField<std::uint8_t> keyDownB{0xA060};
  /// keyDown entry for scan code 31h: masking device while held (8368)
  DataField<std::uint8_t> keyDownN{0xA061};
  /// keyDown entry for scan code 32h: launches a locked missile (8222)
  DataField<std::uint8_t> keyDownM{0xA062};
  /// keyDown entry for scan code 33h: playerSpeed -4 (84B2)
  DataField<std::uint8_t> keyDownComma{0xA063};
  /// keyDown entry for scan code 34h: playerSpeed +4 (849E)
  DataField<std::uint8_t> keyDownPeriod{0xA064};
  /// keyDown entry for scan code 36h: makes ReadScanCode OR 80h into the buffered code
  DataField<std::uint8_t> keyDownRightShift{0xA066};
  /// keyDown entry for scan code 37h: with Alt, the screen dump (GetKey, PollScreenDumpKey); scan code 37h is */PrtSc
  DataField<std::uint8_t> keyDownPrintScreen{0xA067};
  /// keyDown entry for scan code 38h: with PrtSc the screen dump; with W the mis-jump latch
  DataField<std::uint8_t> keyDownAlt{0xA068};
  /// keyDown entry for scan code 39h: fire on the keyboard (ReadFireButton); the pause screen clears it on resume
  DataField<std::uint8_t> keyDownSpace{0xA069};
  /// keyDown entry for scan code 48h: pitch -1 (ReadKeyboardSteering)
  DataField<std::uint8_t> keyDownUp{0xA078};
  /// keyDown entry for scan code 4Bh: roll -1 (ReadKeyboardSteering)
  DataField<std::uint8_t> keyDownLeft{0xA07B};
  /// keyDown entry for scan code 4Dh: roll +1 (ReadKeyboardSteering)
  DataField<std::uint8_t> keyDownRight{0xA07D};
  /// keyDown entry for scan code 50h: pitch +1 (ReadKeyboardSteering)
  DataField<std::uint8_t> keyDownDown{0xA080};
  /// keyDown entry for scan code 77h: Amstrad joystick fire, key code 77h (ReadFireButton)
  DataField<std::uint8_t> keyDownAmstradFire1{0xA0A7};
  /// keyDown entry for scan code 78h: Amstrad joystick fire, key code 78h (ReadFireButton)
  DataField<std::uint8_t> keyDownAmstradFire2{0xA0A8};
  /// keyDown entry for scan code 79h: Amstrad joystick, key code 79h: roll +1 (ReadJoystickSteering)
  DataField<std::uint8_t> keyDownAmstradRight{0xA0A9};
  /// keyDown entry for scan code 7Ah: Amstrad joystick, key code 7Ah: roll -1
  DataField<std::uint8_t> keyDownAmstradLeft{0xA0AA};
  /// keyDown entry for scan code 7Bh: Amstrad joystick, key code 7Bh: pitch +1
  DataField<std::uint8_t> keyDownAmstradDown{0xA0AB};
  /// keyDown entry for scan code 7Ch: Amstrad joystick, key code 7Ch: pitch -1
  DataField<std::uint8_t> keyDownAmstradUp{0xA0AC};
  /// keyDown entry for scan code 7Dh: Amstrad mouse button, key code 7Dh (bit 1 of mouseButtons)
  DataField<std::uint8_t> keyDownAmstradMouseRight{0xA0AD};
  /// keyDown entry for scan code 7Eh: Amstrad mouse button, key code 7Eh (bit 0 of mouseButtons, the fire latch)
  DataField<std::uint8_t> keyDownAmstradMouseLeft{0xA0AE};
  /// ring buffer of make codes, written by ReadScanCode
  DataBlock<16> keyBuffer{0xA0B0};
  /// next write address in keyBuffer
  DataField<std::uint16_t> keyBufferWrite{0xA0C0};
  /// next read address in keyBuffer; GetKey advances it, ResetKeyboard resets it to DS:A0B0
  DataField<std::uint16_t> keyBufferRead{0xA0C2};
  /// keys waiting in keyBuffer; ReadScanCode drops a key when it reaches 16
  DataField<std::uint8_t> keyBufferCount{0xA0C4};
  /// set to 1 by ReadScanCode on an Esc make code; no instruction reads it
  DataField<std::uint8_t> escKeyLatch{0xA0C5};
  /// set to 1 by ReadScanCode on every make code, cleared by the title (7DB3); no instruction reads it
  DataField<std::uint8_t> anyKeyLatch{0xA0C6};
  /// incremented by TimerTick; reset by RateLimit
  DataField<std::uint16_t> timerTicks{0xA0C7};
  /// gates RateLimit
  DataField<std::uint8_t> rateLimitEnabled{0xA0C9};
  /// cursor glyph, a space and a zero: printed after the text by RedrawInputLine; ToggleInputCursor flips the first byte
  DataBlock<3> inputCursorText{0xA0CA};
  /// ReadTextLine's countdown, 300 timer ticks per cursor toggle
  DataField<std::uint16_t> cursorBlinkTicks{0xA0CD};
  /// characters ReadTextLine may still accept
  DataField<std::uint8_t> inputCharsLeft{0xA0CF};
  /// button bits from int 33h AX=5 (or the Amstrad key codes 7Dh/7Eh), written by ReadMouseSteering; no instruction reads it
  DataField<std::uint8_t> mouseButtons{0xA0D0};
  /// byte; ASCII for scan codes 00h-53h (FFh = ignore, 0Dh Enter, 00h Backspace), upper-case letters; used by ReadTextLine
  DataTable<1, 84> scanCodeToAscii{0xA0D1};
  /// last frame's roll direction (-1, 0, +1; 7Fh in the file); ReadKeyboardSteering
  DataField<std::uint8_t> keyboardLastRollKey{0xA125};
  /// last frame's pitch direction (7Fh in the file)
  DataField<std::uint8_t> keyboardLastPitchKey{0xA126};
  /// grows by 1 a frame while the same roll key is held, inside +-23; reset to 0 on any change
  DataField<std::uint8_t> keyboardRollRamp{0xA127};
  /// as keyboardRollRamp, for pitch
  DataField<std::uint8_t> keyboardPitchRamp{0xA128};
  /// as keyboardLastRollKey, for the Amstrad joystick key codes (ReadJoystickSteering)
  DataField<std::uint8_t> amstradStickLastRoll{0xA129};
  /// as keyboardLastPitchKey, for the Amstrad joystick
  DataField<std::uint8_t> amstradStickLastPitch{0xA12A};
  /// as keyboardRollRamp, for the Amstrad joystick
  DataField<std::uint8_t> amstradStickRollRamp{0xA12B};
  /// as keyboardPitchRamp, for the Amstrad joystick
  DataField<std::uint8_t> amstradStickPitchRamp{0xA12C};
  /// port 201h as last read by ReadJoystickAxes; no instruction reads it back
  DataField<std::uint8_t> joystickPortByte{0xA12D};
  /// set to 1 by IBM joystick button A1 (ReadJoystickAxes) or the left mouse button (ReadMouseSteering); never cleared or read
  DataField<std::uint8_t> fireLatch{0xA12E};
  /// ReadJoystickAxes' X count with the stick centred, taken at selection (67BA); ReadJoystickSteering scales against it
  DataField<std::uint16_t> joystickCenterX{0xA12F};
  /// as joystickCenterX, for Y
  DataField<std::uint16_t> joystickCenterY{0xA131};
  /// signed -23..+23: the input code adds to it with clamping (0x79F9) and the steering code stores it (0x84CC, 0x86DF and later); dra...
  DataField<std::uint16_t> rollRate{0xA133};
  /// signed -23..+23: the input code adds to it with clamping (0x7A09); drawn on the DC row (y=161); written with rollRate as one word...
  DataField<std::uint8_t> pitchRate{0xA134};
  /// counts down from 70 (StartBeep); speaker bit 1 = bit 0 of the count, so 500 Hz for 70 ms
  DataField<std::uint8_t> beepTicks{0xA135};
  /// counts down from 70 (StartLowBeep); speaker bit 1 = bit 1 of the count, 250 Hz
  DataField<std::uint8_t> lowBeepTicks{0xA136};
  /// cleared when the docking computer is cancelled, refused or out of range (29FC, 83EA, 8423, 8BB6); no instruction reads it
  DataField<std::uint8_t> dataA137{0xA137};
  /// incremented every tick; bit 9 drives a blink at 0x2914
  DataField<std::uint16_t> millisecondCounter{0xA138};
  /// incremented every tick; compared with minimumFrameMs and cleared by PresentSpaceView
  DataField<std::uint8_t> msSinceFrame{0xA13A};
  /// sweep that toggles the speaker (ToggleSpeaker); started by 0x7B71
  DataField<std::uint8_t> toneSweepActive{0xA13B};
  DataField<std::uint8_t> sirenCountdown{0xA13C};
  DataField<std::uint8_t> sirenStage{0xA13D};
  /// speaker toggled every 15 ticks (33 Hz); only the uncalled 0x7B16 sets it
  DataField<std::uint8_t> humEnabled{0xA13E};
  DataField<std::uint8_t> humCountdownTicks{0xA13F};
  /// sweep that plays noiseSource samples (EmitNoiseSample); started by 0x7AC3, 0x7AFC, 0x7B09
  DataField<std::uint8_t> noiseSweepActive{0xA140};
  DataField<std::uint8_t> sirenHalfTick{0xA141};
  /// one noise sample every tick; only the uncalled 0x7B65 sets it
  DataField<std::uint8_t> continuousNoise{0xA142};
  /// noise samples left, one every 5 ticks; only the uncalled 0x7B45 sets it (50)
  DataField<std::uint8_t> slowNoiseCount{0xA143};
  DataField<std::uint8_t> slowNoiseDivider{0xA144};
  /// samples per step; falls by sweepStepShrink each step
  DataField<std::uint8_t> sweepStepLength{0xA145};
  /// 2: 250 Hz, then 1: 500 Hz, 300 ticks each; only the uncalled 0x7B22 sets it
  DataField<std::uint8_t> twoToneStage{0xA146};
  DataField<std::uint16_t> twoToneTicks{0xA147};
  /// ticks to the next sample
  DataField<std::uint8_t> sweepTickCounter{0xA149};
  /// samples left in this step
  DataField<std::uint8_t> sweepStepCounter{0xA14A};
  /// ticks between samples; +1 a step, the sweep ends at 7
  DataField<std::uint8_t> sweepPeriodTicks{0xA14B};
  /// 2-8 by effect
  DataField<std::uint8_t> sweepStepShrink{0xA14C};
  /// one noise sample a tick while nonzero; 100 from 0x7B96
  DataField<std::uint8_t> noiseBurstTicks{0xA14D};
  /// 0-0x3FF into noiseSource, advanced by EmitNoiseSample
  DataField<std::uint16_t> noiseSourceIndex{0xA14E};
  /// acts every other tick: 125 Hz for 100 actions, then 250 Hz and 125 Hz alternating (150 and 75 actions) until stopped; only the un...
  DataField<std::uint8_t> sirenEnabled{0xA150};
  /// silent tail of the current note
  DataField<std::uint16_t> noteGapTicks{0xA151};
  DataField<std::uint16_t> noteTicksLeft{0xA153};
  /// when 1, TimerTick plays the tune at musicPointer on PIT channel 2
  DataField<std::uint8_t> musicPlaying{0xA155};
  /// next note; 0x47 restarts at DS:A1B4
  DataField<std::uint16_t> musicPointer{0xA156};
  /// word; PIT channel 2 divisors, index = note-12 (8609 = 138.6 Hz ... 640)
  DataTable<2, 46> notePeriods{0xA158};
  /// word; note words for TimerTickMusic, started by StartMusic
  DataAt titleTune{0xA1B4};
  /// integrated roll for the keyboard and the Amstrad joystick, +-23; ReadSteering stores AX here (word with keyboardPitchRate)
  DataField<std::uint8_t> keyboardRollRate{0xA5B4};
  /// integrated pitch, as keyboardRollRate
  DataField<std::uint8_t> keyboardPitchRate{0xA5B5};
  /// set by ReadScanCode when D (20h) is released while inFlight; ProcessFlightKeys then toggles the docking computer if fitted; clear...
  DataField<std::uint8_t> dockingKeyReleased{0xA5B6};
  /// FFh in the file; 0 cockpit (ShowCockpitScreen), 1 chart frame (DrawChartFrame), 2 text mode (DrawDockedFrame); also selects the t...
  DataField<std::uint8_t> screenLayout{0xA7D0};
  /// CGA text attribute for PrintTextModeString; DrawDockedFrame sets it from the frame's first byte
  DataField<std::uint8_t> textAttribute{0xA7D1};
  /// word cell offset, byte CP437 character; the docked frame's corners and tees: C9h at 0, BBh at 4Eh, CCh at A0h, B9h at EEh, C8h at...
  DataTable<2, 6> frameCorners{0xA7D3};
  /// 1 while RunFlight's loop owns the screen (GameLoop), 0 on the title and docked screens and while HandleFlightFunctionKeys runs a...
  DataField<std::uint8_t> inFlight{0xA7F0};
  /// set when laser kind 2 (Mining, names at DS:81C2) hits type 5 (0x8AEC); fragments get slower, live 60 frames longer, and may carry...
  DataField<std::uint8_t> miningLaserOnAsteroid{0xA7F1};
  /// 80 when the capsule launches (2F14); TickEscapePod counts it down and ends RunFlight; also suppresses enemy fire; while non-zero...
  DataField<std::uint8_t> escapePodFrames{0xA7F2};
  /// set when H is pressed inside the galactic drive window; CompleteHyperspaceJump then makes a galactic jump
  DataField<std::uint8_t> galacticJumpPending{0xA7F3};
  /// 'ID Indicator Activated'
  DataAt idIndicatorMessage{0xA7F4};
  /// 40 when G arms the galactic drive; H within that window starts a galactic jump
  DataField<std::uint8_t> galacticDriveReadyFrames{0xA825};
  /// 'Galactic Drive Motor Ready'
  DataAt galacticDriveReadyMessage{0xA826};
  /// 'Prepare to Hyperspace...' followed by hyperspaceCountdownDigits
  DataAt hyperspaceCountdownMessage{0xA841};
  /// two ASCII digits at the end of hyperspaceCountdownMessage, written by ShowHyperspaceCountdown
  DataField<std::uint16_t> hyperspaceCountdownDigits{0xA859};
  /// 10 when the countdown starts, -1 every 10 frames; arrival at 0
  DataField<std::uint8_t> hyperspaceCountdown{0xA85C};
  /// frames left in the current countdown step (10)
  DataField<std::uint8_t> hyperspaceCountdownFrames{0xA85D};
  /// 'System Outside Hyperspace Range!'
  DataAt outOfRangeMessage{0xA85E};
  /// 'Hyperspace System not Selected!'
  DataAt noSystemSelectedMessage{0xA87F};
  /// 'Not Enough Fuel to Hyperspace'
  DataAt notEnoughFuelMessage{0xA89F};
  /// 'Nav-Comp now repaired!'
  DataAt navCompRepairedMessage{0xA8BD};
  /// 'Hyperspace Drive is Being Jammed!'
  DataAt hyperspaceJammedMessage{0xA8D4};
  /// 1 while the docking computer flies the ship (UpdatePlayerMotion calls RunDockingComputer)
  DataField<std::uint8_t> dockingComputerOn{0xA8F6};
  /// RunDockingComputer's steering, AL=roll, AH=pitch
  DataField<std::uint16_t> dockingComputerSteering{0xA8F7};
  /// RunDockingComputer's state, 0-11
  DataField<std::uint8_t> dockingComputerState{0xA8F9};
  /// 1 after 0x7E90; makes RunTitleAndDocked reopen ShowDiscControlScreen to show the result; cleared when an F-key leaves it
  DataField<std::uint8_t> resumeAtDiskMenu{0xA8FD};
  /// 1 once the title has run; cleared on death (GameLoop) and by Abort on the pause screen, so the title runs again
  DataField<std::uint8_t> titleShown{0xA8FE};
  /// 'Press any key to start game' (title)
  DataAt pressAnyKeyText{0xA966};
  /// '---- E L I T E ----'
  DataAt eliteTitleText{0xA982};
  /// negated new pitch angle while UpdatePlayerMotion re-derives the orientation
  DataField<std::uint16_t> pitchAngleScratch{0xA9AF};
  /// negated new yaw angle, as pitchAngleScratch
  DataField<std::uint16_t> yawAngleScratch{0xA9B1};
  /// per-frame displacement subtracted from every object by MoveObjectsByVelocity
  DataField<std::uint16_t> playerVelocityX{0xA9B3};
  /// see playerVelocityX
  DataField<std::uint16_t> playerVelocityY{0xA9B5};
  /// see playerVelocityX
  DataField<std::uint16_t> playerVelocityZ{0xA9B7};
  /// 4-48 in steps of 4 (. and ,), 0 while the docking computer stops the ship; the jump drive needs 48
  DataField<std::uint16_t> playerSpeed{0xA9B9};
  /// 1 makes UpdatePlayerVelocity recompute the velocity
  DataField<std::uint8_t> velocityDirty{0xA9BB};
  /// angle RunDockingComputer is turning to
  DataField<std::uint16_t> dockingTargetAngle{0xA9BC};
  /// each alignment phase of RunDockingComputer runs twice
  DataField<std::uint8_t> dockingAlignPasses{0xA9BE};
  /// 'E.C.M. Active Now'
  DataAt ecmActiveMessage{0xA9BF};
  /// 'Docking Computer Disengaged'
  DataAt dockingComputerOffMessage{0xA9D1};
  /// 'Docking Computer Locked On'
  DataAt dockingComputerOnMessage{0xA9ED};
  /// 'Station not in Lock-on Range'
  DataAt stationOutOfRangeMessage{0xAA08};
  /// 'Jump Drive Engaged'
  DataAt jumpDriveEngagedMessage{0xAA45};
  /// 'Jump Drive is Mass-Locked'
  DataAt jumpDriveMassLockedMessage{0xAA58};
  /// 'Jump Drive is Velocity-Locked'
  DataAt jumpDriveVelocityLockedMessage{0xAA72};
  /// 'Game Paused'
  DataAt gamePausedMessage{0xAA90};
  /// 'Missile Launched'
  DataAt missileLaunchedMessage{0xAA9C};
  /// 'Missile Locked-on Target!'
  DataAt missileLockedMessage{0xAAAD};
  /// 'Missile Primed'
  DataAt missilePrimedMessage{0xAAC7};
  /// 'Missile Unarmed'
  DataAt missileUnarmedMessage{0xAAD6};
  /// 1 for one frame after J: UpdatePlayerVelocity multiplies the playerSpeed by 32
  DataField<std::uint8_t> jumpDriveEngaged{0xAAE6};
  /// F1 0, F2 400h, F3 200h, F4 600h (800h per turn); 0 front, 0x200 left, 0x400 rear, 0x600 right; RotateToViewDirection
  DataField<std::uint16_t> viewAngle{0xAAE7};
  /// set by the docking computer's final approach; F1-F4 are ignored while 1
  DataField<std::uint8_t> viewLocked{0xAAE9};
  /// slot the missile is locked on
  DataField<std::uint16_t> missileTarget{0xAAEA};
  /// laser type (0-3) for this view, from GetViewLaser; damage is type + 1; set at 0x8297 when fire is pressed; DrawLaserBeams picks i...
  DataField<std::uint8_t> firingLaserType{0xAAEC};
  /// 1 for the frame the laser fires; ResolveLaserFire clears it
  DataField<std::uint8_t> laserFiring{0xAAED};
  /// word; per ship type ([di] & 3Eh), the size FindShipInCrosshairs tests against; 30 used, the last two 0
  DataTable<2, 32> shipTargetRadius{0xAAEE};
  /// toggled on each frame a type-0 laser is fired; that type fires only on alternate frames
  DataField<std::uint8_t> laserAlternateFrame{0xAB2E};
  /// 1 after I until the ship in the sights is identified
  DataField<std::uint8_t> shipIdRequested{0xAB2F};
  /// 40 at death; RunFlight keeps running frames until it reaches 0
  DataField<std::uint8_t> gameOverFrames{0xAB30};
  /// 'GAME OVER!'
  DataAt gameOverMessage{0xAB31};
  /// word buffer offset, then zero-terminated text; the pause screen's lines: SPACE..Restart Game, A......Abort Game, R Keyboard Recen...
  DataTable<2, 8> pauseMenuText{0xAB3C};
  /// the '8) ' of '(F8) ' at the end of the pause menu's frame-rate line; rewritten by F1-F10
  DataBlock<3> frameRateKeyLabel{0xABFF};
  DataField<std::uint8_t> dataAC00{0xAC00};
  DataField<std::uint8_t> dataAC01{0xAC01};
  /// pause option R, 'Keyboard Recentre', 1 in the file: a key against the current rate zeroes it first. First of five (value, letter)...
  DataField<std::uint8_t> keyboardRecenter{0xAC03};
  /// pause option D, 'Keyboard Damping', 1 in the file: an idle axis decays 3 a frame toward 0
  DataField<std::uint8_t> keyboardDamping{0xAC05};
  /// pause option Y, 'Reverse Y control', 0 in the file: negates pitch (ApplyReverseControls)
  DataField<std::uint8_t> reverseYControl{0xAC07};
  /// pause option B, 'Reverse X and Y', 0 in the file: negates roll and pitch
  DataField<std::uint8_t> reverseXAndY{0xAC09};
  /// pause option S, 'Sound Toggle', 1 in the file; TimerTick does nothing more when it is 0
  DataField<std::uint8_t> soundEnabled{0xAC0B};
  /// colour-select value UpdateDamageFlash writes each frame: 9 (bright blue) while the masking device runs, else 0 (cleared at 4A4C);...
  DataField<std::uint8_t> maskingBackgroundColor{0xAC0D};
  /// toggled by 'L' (0x8379, 0x838C) when antiEcmEmulatorFitted; at 1 the station starts no ECM
  DataField<std::uint8_t> antiEcmActive{0xAC0E};
  /// TimerTick plays nothing while it is 1
  DataField<std::uint8_t> gamePaused{0xAC0F};
  /// nine zero-terminated lines: Game Copyright:- Bell & Braben, Code Copyright:- Realtime Games Software Ltd, Written by:- Andy Onion...
  DataAt creditsScreenText{0xAC10};
  /// ship type shown on the title (1Ah in the file), F9/F10 step it through 2-29
  DataField<std::uint8_t> titleShipType{0xACB4};
  /// word; title display distance per ship type
  DataTable<2, 30> titleShipDistances{0xACB5};
  /// byte; 200, 125, 100, 83, 67, 56, 50, 40, 30, 1 ms, chosen with F1-F10 on the pause screen
  DataTable<1, 10> frameTimeChoices{0xACF1};
  /// 50 in the file, which is F7's choice, though the label in the file reads (F8) (40 ms); the shortest a frame may take
  DataField<std::uint8_t> minimumFrameMs{0xACFB};
  /// set on a 500/65536 chance at launch (Missile Jammed... Can't Launch!); M then fails until reset at 2A33
  DataField<std::uint8_t> missileJammed{0xACFC};
  /// 'Missile Jammed... Can't Launch!'
  DataAt missileJammedMessage{0xACFD};
  /// 'Missile Target Destroyed'
  DataAt missileTargetDestroyedMessage{0xAD1D};
  /// 'Docking Permission Denied!'
  DataAt dockingDeniedMessage{0xAD36};
  /// word; a copy of spanLeftMasks and spanRightMasks at the bottom of the stack segment (SS:0000 = DS:AD60; the MZ header's SS is 13C...
  DataTable<2, 8> triangleEdgeMasks{0xAD60};
  /// the cockpit and dashboard as a mode 4 screen (two 8000-byte banks); ShowCockpitScreen copies it from segment 140Ah. Above the sta...
  DataBlock<16000> cockpitImage{0xB160};
};

/// The overlay native code uses: `DS.playerDocked`.
inline constexpr DataOverlay DS{};

} // namespace Elite
