#include "pch.h"

#include "LookupTables.h"

/*
 * GENERATED by tools/extract_tables.py -- do not edit by hand.
 *
 * Extracted by label and length from the assembled Commodore 64 build, and the port's own
 * data since 2026-09-07: nothing compares it against the original any more.
 */

namespace Elite
{
  // The price of each item, in tenths.
  constexpr std::array<std::uint8_t, 28> EQUIPMENT_PRICES = {
    0x01, 0x00, 0x2C, 0x01, 0xA0, 0x0F, 0x70, 0x17, 0xA0, 0x0F, 0x10, 0x27, 0x82, 0x14,
    0x10, 0x27, 0x28, 0x23, 0x98, 0x3A, 0x10, 0x27, 0x50, 0xC3, 0x60, 0xEA, 0x40, 0x1F,
  };

} // namespace Elite
