#pragma once

#include <array>
#include <cstdint>

/*
 * The tables the game computes with instead of calculating (ADR-002 section 2).
 *
 * Elite multiplies and divides through logarithms for the cases where shift-and-add is too
 * slow, and it takes sine and arctangent straight out of a table. All of it is data rather
 * than arithmetic, so the port uses the same bytes rather than calling into <cmath> and hoping
 * the answers agree. They would not: the tables carry rounding decisions that the game's
 * results depend on.
 *
 * The arrays are GENERATED by tools/extract_tables.py, straight out of the assembled game, and
 * TableTests.cpp compares each one against the same address range in the oracle's image. An
 * edited or stale table therefore fails a test rather than quietly changing the universe.
 *
 * This header is written by hand: the tool owns the bytes, and the interface stays put.
 */

namespace Elite
{

// 6502: log, logL -- the two halves of a logarithm, indexed by the value.
extern const std::array<std::uint8_t, 256> LOG_TABLE;
extern const std::array<std::uint8_t, 256> LOG_LOW_TABLE;

// 6502: antilog, antilogODD -- the inverse. Which one applies depends on a parity test the
// multiply makes on the way through, so both are needed.
extern const std::array<std::uint8_t, 256> ANTILOG_TABLE;
extern const std::array<std::uint8_t, 256> ANTILOG_ODD_TABLE;

// 6502: SNE -- a quarter turn of sine, scaled to a byte.
extern const std::array<std::uint8_t, 32> SINE_TABLE;

// 6502: ACT -- arctangent, indexed by a ratio the caller has already reduced.
extern const std::array<std::uint8_t, 32> ARCTAN_TABLE;

// 6502: QQ18 -- the recursive token table: runs of text separated by zero bytes, each character
// exclusive-ored against RECURSIVE_TOKEN_KEY. A token number is an index counted in terminators
// rather than an offset, which is why reading one means walking the table.
extern const std::array<std::uint8_t, 960> RECURSIVE_TOKEN_TABLE;

// 6502: QQ16 -- pairs of letters, indexed by token. A '?' in the second position means the pair
// is really a single letter.
extern const std::array<std::uint8_t, 69> TWO_LETTER_TABLE;

// 6502: TKN1 -- the extended token table. Same shape as the recursive one, a different key, and
// a richer language: its bytes can be control codes, nested tokens or randomised variants.
extern const std::array<std::uint8_t, 3112> EXTENDED_TOKEN_TABLE;

// 6502: TKN2 -- letter pairs for the extended tokens, reached from the top of the byte range.
// Every value from 215 to 255 indexes this, so it runs to offset 81 and overlaps the table that
// follows it in memory. Elite shares address space between tables where the ranges allow it.
extern const std::array<std::uint8_t, 82> EXTENDED_PAIR_TABLE;

// 6502: RUTOK -- description overrides for particular systems, walked exactly like TKN1.
extern const std::array<std::uint8_t, 625> SYSTEM_TOKEN_TABLE;

// 6502: MTIN -- for each token that has randomised variants, the first of them.
extern const std::array<std::uint8_t, 38> VARIANT_BASE_TABLE;

} // namespace Elite
