#pragma once

#include <array>
#include <cstdint>

/*
 * The tables the game computes with instead of calculating (ADR-002 section 2).
 *
 * Elite multiplies and divides through logarithms for the cases where shift-and-add is too
 * slow, and it takes sine and arctangent straight out of a table. All of it is data rather
 * than arithmetic, so the port uses the same bytes rather than calling into <cmath> and hoping
 * the answers agree. They would not: the tables carry rounding decisions that the game's
 * results depend on.
 *
 * The arrays are GENERATED by tools/extract_tables.py, straight out of the assembled game, and
 * TableTests.cpp compares each one against the same address range in the oracle's image. An
 * edited or stale table therefore fails a test rather than quietly changing the universe.
 *
 * This header is written by hand: the tool owns the bytes, and the interface stays put.
 */

namespace Elite
{

  // 6502: log, logL -- the two halves of a logarithm, indexed by the value.
  extern const std::array<std::uint8_t, 256> LOG_TABLE;
  extern const std::array<std::uint8_t, 256> LOG_LOW_TABLE;

  // 6502: antilog, antilogODD -- the inverse. Which one applies depends on a parity test the
  // multiply makes on the way through, so both are needed.
  extern const std::array<std::uint8_t, 256> ANTILOG_TABLE;
  extern const std::array<std::uint8_t, 256> ANTILOG_ODD_TABLE;

  // 6502: SNE -- a quarter turn of sine, scaled to a byte.
  extern const std::array<std::uint8_t, 32> SINE_TABLE;

  // 6502: ACT -- arctangent, indexed by a ratio the caller has already reduced.
  extern const std::array<std::uint8_t, 32> ARCTAN_TABLE;

  // 6502: QQ18 -- the recursive token table: runs of text separated by zero bytes, each character
  // exclusive-ored against RECURSIVE_TOKEN_KEY. A token number is an index counted in terminators
  // rather than an offset, which is why reading one means walking the table.
  extern const std::array<std::uint8_t, 960> RECURSIVE_TOKEN_TABLE;

  // 6502: QQ16 -- pairs of letters, indexed by token. A '?' in the second position means the pair
  // is really a single letter.
  extern const std::array<std::uint8_t, 69> TWO_LETTER_TABLE;

  // 6502: TKN1 -- the extended token table. Same shape as the recursive one, a different key, and
  // a richer language: its bytes can be control codes, nested tokens or randomised variants.
  extern const std::array<std::uint8_t, 3112> EXTENDED_TOKEN_TABLE;

  // 6502: TKN2 -- letter pairs for the extended tokens, reached from the top of the byte range.
  // Every value from 215 to 255 indexes this, so it runs to offset 81 and overlaps the table that
  // follows it in memory. Elite shares address space between tables where the ranges allow it.
  extern const std::array<std::uint8_t, 82> EXTENDED_PAIR_TABLE;

  // 6502: RUTOK -- description overrides for particular systems, walked exactly like TKN1.
  extern const std::array<std::uint8_t, 625> SYSTEM_TOKEN_TABLE;

  // 6502: MTIN -- for each token that has randomised variants, the first of them.
  extern const std::array<std::uint8_t, 38> VARIANT_BASE_TABLE;

  /*
   * The screen tables (slice 1d).
   *
   * Every one is indexed by a value the caller has already masked, and the array length is what
   * that mask can reach rather than the gap to the next label -- Elite overlaps its tables where
   * the ranges allow (plan section 6.8).
   *
   * The two-bit multicolour pixel is the thing to keep in mind reading these: a byte is four
   * pixels, so a mask that looks like it covers "one pixel" may cover a bit of two.
   */

  // 6502: TWOS -- one pixel of a line, selected by x within the byte. LOIN part 5 reads it with
  // x AND 7. On this lineage the masks slide by one bit, so half of them straddle two multicolour
  // pixels; that is the game's behaviour, not a porting artefact (ADR-002 section 7).
  extern const std::array<std::uint8_t, 8> PIXEL_MASK_TABLE;

  // 6502: TWOS2 -- the mark PIXEL plots, again by x AND 7, and again bit-sliding rather than
  // pixel-aligned.
  extern const std::array<std::uint8_t, 8> DASH_MASK_TABLE;

  // 6502: CTWOS2 -- the multicolour-ALIGNED masks, two identical entries per pixel so that a pair
  // of x values share one. CPIX2 and SCAN read it as CTWOS2+2,X with x AND 7, which is why it runs
  // to ten entries rather than eight.
  extern const std::array<std::uint8_t, 10> MULTICOLOUR_MASK_TABLE;

  // 6502: DTWOS -- one aligned multicolour pixel by pixel number. Nothing in the C64 build indexes
  // it; it is here because the ledger names it and it is four bytes.
  extern const std::array<std::uint8_t, 4> DASHBOARD_MASK_TABLE;

  /*
   * 6502: CTWOS -- the same four masks again, at a different address, and this is the one the
   * dashboard reads (slice 3d-b).
   *
   * `DIL2` indexes it with a bar position below four, which is what sizes it; the listing carries a
   * fifth byte past that, a repeat of the first, which nothing can reach. It holds the same values
   * as `DTWOS` and is extracted separately anyway: two labels at two addresses are two tables, and
   * one array shared between them would be the port asserting something the game does not (§6.63).
   */
  extern const std::array<std::uint8_t, 4> DASHBOARD_PIXEL_TABLE;

  // 6502: TWFR, TWFL -- a horizontal line's end bytes: TWFR fills from x rightwards to the end of
  // the byte, TWFL fills leftwards from the start of the byte to x. Everything between is 0xFF.
  extern const std::array<std::uint8_t, 8> LINE_RIGHT_MASK_TABLE;
  extern const std::array<std::uint8_t, 8> LINE_LEFT_MASK_TABLE;

  // 6502: ylookupl, ylookuph -- the bitmap address of screen row y, which is
  // SCBASE + 0x20 + (y >> 3) * 320. The 0x20 is the space view's four-cell left margin.
  // Canvas computes that arithmetic directly; these are kept so a test can prove the two agree
  // for all 256 rows, and so the oracle has something to compare against.
  extern const std::array<std::uint8_t, 256> ROW_ADDRESS_LOW;
  extern const std::array<std::uint8_t, 256> ROW_ADDRESS_HIGH;

  // 6502: celllookl, celllookh -- the colour-cell address of a character row, which is
  // SCBASE + 0x2003 + 40 * row. The three-cell offset is not a margin: CHPR writes the colour
  // after advancing the cursor, so celllook[row] + (XC + 1) lands on cell 4 + XC, the same cell
  // the glyph went into.
  extern const std::array<std::uint8_t, 25> CELL_ADDRESS_LOW;
  extern const std::array<std::uint8_t, 25> CELL_ADDRESS_HIGH;

  // 6502: TENS -- the low four bytes of 10^11. The most significant byte is not here: BPRNT
  // subtracts it as an immediate 0x17, so the whole constant is 0x17_4876E800.
  extern const std::array<std::uint8_t, 4> TEN_TO_THE_ELEVENTH;

  // 6502: QQ23 -- the market table: base price, economy gradient, base quantity and random mask,
  // four bytes for each of the seventeen goods.
  extern const std::array<std::uint8_t, 68> MARKET_TABLE;

  /*
   * 6502: PRXS -- what each piece of equipment costs, two bytes an item, low byte first, in tenths
   * of a credit.
   *
   * FOURTEEN items, not the twelve the cassette version sells: the C64 build adds the military and
   * mining lasers at the end. Entry 0 is a placeholder of 1 that EQSHP overwrites before it reads
   * the table, because the price of fuel depends on how empty the tank is.
   */
  extern const std::array<std::uint8_t, 28> EQUIPMENT_PRICES;

  // 6502: FONT -- 96 characters of eight rows, starting at space. One bit per pixel here; CHPR
  // doubles each bit into a multicolour pixel on the way to the bitmap.
  extern const std::array<std::uint8_t, 768> FONT_DATA;

  /*
   * 6502: NA2% -- the commander the game starts from.
   *
   * Eight bytes of name and then the 77-byte data block, and thirteen more because JAMESON copies
   * ninety-eight rather than the eighty-five the two come to. The extra bytes are copied by the
   * game and so are extracted by the port; nothing reads them.
   */
  extern const std::array<std::uint8_t, 98> DEFAULT_COMMANDER;

  /*
   * 6502: TRANTABLE -- the character `TT217` hands back for each internal key number.
   *
   * The C64's keyboard produces a MATRIX POSITION, not a character, and `RDKEY` returns that
   * position: 0 to 64, which is why `ZEKTRAN` clears sixty-five bytes of the key logger. This is
   * the table that turns one into the other, and it is game data rather than platform policy --
   * every routine that compares a key against `'1'` or `'Y'` or 13 is comparing against what this
   * produced, so a shell that invented its own mapping would be playing a different game.
   *
   * It is worth knowing that the two halves are BOTH used. `TT102` dispatches on the raw position
   * (`f8` is 37, not `'8'`); every docked screen reads the translated character through the
   * `KeySource` seam. So the executable needs the position for one and this table's output for the
   * other, from the same key press.
   *
   * Entry 0 is 0, which is `RDKEY`'s "no key" -- so the table's own identity for "nothing pressed"
   * is a character the text system will not print.
   */
  extern const std::array<std::uint8_t, 65> KEY_TRANSLATION;

  /*
   * 6502: XX21 through the last ship blueprint -- the whole ship data region, addressed as the
   * game addresses it (slice 3a).
   *
   * ONE ARRAY AND NOT THIRTY-THREE, and that is a finding rather than a preference. Two blueprints
   * declare more data in their header than fits before the next one begins (the splinter by 24
   * bytes, the Thargon by 60), and those same two are the only ships with no `_EDGES` label, so
   * the labels cannot arbitrate; a third has four bytes of slack. Slicing per ship would truncate
   * two of them or hand them their neighbour's bytes. Plan §6.32 has the measurements.
   *
   * Underneath that is the reason it was never going to work: the game has NO CONCEPT of where a
   * blueprint ends. `NWSHP` puts an address into `XX0` and every read is `LDA (XX0),Y`. So the
   * port keeps the region and the addresses, and `ShipBlueprint.h` is the indexing.
   *
   * The size is derived, not chosen -- `tools/extract_tables.py` computes it from the last
   * blueprint's own header -- so if it ever changed this declaration would stop compiling, which is
   * the failure worth having.
   */
  extern const std::array<std::uint8_t, 8073> SHIP_DATA;

  /*
   * 6502: scacol -- what colour a ship's blip is on the scanner, by ship type (slice 3d).
   *
   * The colours are FOUR MULTICOLOUR PIXELS EACH and not colour numbers, which is why they read as
   * 0x55, 0xAA, 0xFF and 0x5A: `SCAN` ANDs the entry with the pixel mask, so a "colour" here is a
   * bit pattern that survives the AND. `RED` is %01 four times, `YELLOW` %10 four times, `GREEN`
   * %11 four times, and `WHITE` is %01 %01 %10 %10 -- the striped blip a Thargoid gets.
   *
   * THREE OF THE NAMES ARE THE SAME COLOUR. `BLUE`, `CYAN` and `MAG` are all defined as `YELLOW`
   * on this build, so the escape pod, the Cobra and the Python come out the same yellow the
   * listing's three different names suggest they would not. Twenty-one of the thirty-four entries
   * are 0xAA for that reason.
   *
   * Entry 0 is the empty slot and entry 32 is the Cougar, both zero -- a blip ANDed to nothing,
   * which is a ship that leaves no mark. Sized by what can index it, as `MANY` is.
   */
  extern const std::array<std::uint8_t, 34> SCANNER_COLOUR_TABLE;

  /*
   * 6502: sightcol -- the colour of the laser sights, by which laser is fitted.
   *
   * A colour NUMBER here rather than a bit pattern, unlike the scanner table above it, because the
   * sights are a sprite and this goes straight into the VIC-II's sprite colour register.
   *
   * Indexed as `sightcol-SPOFF%,Y` with Y the sprite pointer the routine has just chosen, so the
   * table is walked in the same order the four `CMP`s test: pulse, beam, military, and then
   * anything else, which is the mining laser by elimination rather than by name. Pulse and beam
   * are both 7, so two of the four entries are indistinguishable in play.
   */
  extern const std::array<std::uint8_t, 4> LASER_SIGHT_COLOUR_TABLE;

  /*
   * 6502: TRIBTA and TRIBMA -- the Trumble population, turned into sprites.
   *
   * `SIGHT` masks the high byte of the count to `AND #%01111111` and shifts it right four times, so
   * the index is 0 to 7 and both tables have eight entries. `TRIBTA` is how many sprites that many
   * Trumbles are worth and `TRIBMA` is which of the eight VIC-II sprites to switch on for it.
   *
   * BOTH END ON A REPEAT. Entries 6 and 7 are identical in each, so a hold with 112 Trumbles looks
   * exactly like one with 255 of them: the population saturates rather than wrapping round to
   * nothing, which is what the table is for.
   */
  extern const std::array<std::uint8_t, 8> TRUMBLE_COUNT_TABLE;
  extern const std::array<std::uint8_t, 8> TRUMBLE_SPRITE_TABLE;

  /*
   * 6502: DSTORE% -- the dashboard picture, which `wantdials` copies into the bitmap.
   *
   * Seven character rows of forty cells at eight bytes each is 2,240, and this is 2,241. The
   * labels, the bar frames, the scanner's ellipse and the word ELITE are all in here as pixels:
   * the game draws only what MOVES, and this is everything that does not.
   *
   * THE COPY IS 2,240 BYTES AND THEY ARE NOT THE FIRST 2,240. `wantdials` copies eight whole pages
   * and then re-enters the copier at `mvbllop` with Y = &C0, and that entry stores at Y and counts
   * DOWN to 1 -- so the last byte it reaches is offset 2,240 and the byte at offset 2,048 is never
   * touched at all. Both happen to be zero, so the hole and the overrun are invisible on screen and
   * neither is invisible to a byte-for-byte comparison.
   *
   * THE ONLY TABLE HERE THAT NO ASSEMBLY STEP PRODUCES. The image ships inside `COMLOD.bin` and
   * the C64's own loader places it at `DSTORE%`, so BeebAsm never emits a label for it and the
   * address comes from the source's `SCBASE + &AF90`. Before `Binaries.txt` carried the row, the
   * oracle held zeros there — and a comparison of `wantdials` would have copied blanks on both
   * sides and agreed (§6.78).
   *
   * IT OPENS WITH 24 ZEROS, AND THEY ARE THE PICTURE'S ALIGNMENT. The loader reads the file in at
   * `DSTORE% + &18`, so the artwork starts three cells along and the first 24 bytes are whatever
   * was already at `DSTORE%` — nothing, in a machine that has just booted. Put the file at
   * `DSTORE%` instead and the whole dashboard shifts three cells left: it still reads as a
   * dashboard, which is how the port shipped it that way, and every label sits outside the box it
   * belongs in. What settles it is the colour map, not the picture (§6.105).
   */
  extern const std::array<std::uint8_t, 2241> DASHBOARD_IMAGE;

  /*
   * 6502: sdump and cdump -- the colours that dashboard picture is drawn IN.
   *
   * `DASHBOARD_IMAGE` above is bits, and bits have no colour: what the VIC-II makes of them comes
   * from screen RAM and colour RAM, and these two are what the C64's loader fills those with
   * before the game starts. Leave them out and `wantdials` still copies all 2,240 bytes, all seven
   * rows still land exactly where they belong, and the whole dashboard is black on black.
   *
   * THE THREE OF THEM ARE ONE PICTURE. The dashboard is the only part of the screen in multicolour
   * bitmap mode, where a PAIR of bits chooses between four colours: %00 the background register,
   * %01 the high nibble of `sdump`'s byte for that cell, %10 its low nibble, and %11 the low
   * nibble of `cdump`'s. So &27 in `sdump` with &0D in `cdump` is a cell whose three ink colours
   * are dark grey, red and light green -- the scanner -- and it takes both tables to say that.
   *
   * 280 BYTES, WHICH IS SEVEN ROWS OF FORTY, and `mvsm` copies them to offset &2D0 of each: 18 *
   * 40, the first cell of character row 18, which is where the dashboard starts. The next label is
   * 288 bytes on, so the eight bytes between are not part of either table (§6.8).
   *
   * These are the only two things this port takes out of `elite-loader.asm`, whose code is not
   * ported. They are also the only two extracted from a different 64 KB image: the loader loads at
   * &4000, over the game's own screen bitmap, so it is assembled into a space of its own that the
   * oracle never sees.
   */
  extern const std::array<std::uint8_t, 280> DASHBOARD_SCREEN_COLOURS;
  extern const std::array<std::uint8_t, 280> DASHBOARD_COLOUR_RAM;

} // namespace Elite
