#include "pch.h"

#include "LookupTables.h"

/*
 * GENERATED by tools/extract_tables.py -- do not edit by hand.
 *
 * Extracted by label and length from the assembled Commodore 64 build. The companion
 * test compares every array here against the same address range in the oracle's image,
 * so an edit or a stale regeneration fails rather than drifting quietly.
 */

namespace Elite
{
  // 6502: TGINT -- the key each configuration toggle answers to, in the order `DKS3` walks `DAMP`.
  const std::array<std::uint8_t, 13> OPTION_KEY_TABLE = {
    0x01, 0x36, 0x29, 0x2B, 0x27, 0x1E, 0x1B, 0x1C, 0x2E, 0x17, 0x2C, 0x32, 0x24,
  };

} // namespace Elite
