#include "pch.h"

#include "LookupTables.h"

/*
 * GENERATED by tools/extract_tables.py -- do not edit by hand.
 *
 * Extracted by label and length from the assembled Commodore 64 build. The companion
 * test compares every array here against the same address range in the oracle's image,
 * so an edit or a stale regeneration fails rather than drifting quietly.
 */

namespace Elite
{
  // 6502: SNE -- a quarter turn of sine, scaled to a byte.
  const std::array<std::uint8_t, 32> SINE_TABLE = {
    0x00, 0x19, 0x32, 0x4A, 0x62, 0x79, 0x8E, 0xA2, 0xB5, 0xC6, 0xD5, 0xE2, 0xED, 0xF5, 0xFB, 0xFF,
    0xFF, 0xFF, 0xFB, 0xF5, 0xED, 0xE2, 0xD5, 0xC6, 0xB5, 0xA2, 0x8E, 0x79, 0x62, 0x4A, 0x32, 0x19,
  };

} // namespace Elite
