#!/usr/bin/env python3
"""Export the port's bitmap arrays to BMP files, and import an edited BMP back into the array.

THREE OF THE GENERATED TABLES ARE PICTURES, and a picture is not something to edit as hex. This
tool knows each of them by the name of its array, knows how the bytes lay out into pixels, and
carries the pixels out to a BMP a paint program can open and back in again:

    FONT_DATA            96 characters of 8x8, one bit per pixel, laid out 16 across and 6 down
    DASHBOARD_IMAGE      the dashboard picture, 40 cells by 7 rows, two bits per pixel (160x56)
    SPRITE_DEFINITIONS   seven hardware sprites side by side, each in a 24-pixel-wide slot

    python tools/bitmaps.py --list                        # the arrays it knows and their sheets
    python tools/bitmaps.py export [--out DIR] [NAME ...] # write DIR/NAME.bmp for each (default: all)
    python tools/bitmaps.py import NAME FILE.bmp          # rewrite NAME's bytes in its .cpp from FILE
    python tools/bitmaps.py --self-test                   # prove export then import is the identity

WHAT A PIXEL MEANS. A pixel's palette index IS its bit value: 0 or 1 in a hi-res picture, 0 to 3 in
a multicolour one. The colours in the palette are only there to make the bits visible in an editor
-- they are not the colours the game shows, because on the C64 those live in screen RAM and colour
RAM per cell and in the sprite colour registers, none of which is in these arrays (see
`DASHBOARD_SCREEN_COLOURS` and `VideoState.h`). So an editor must paint with the palette's own four
colours and nothing else: the import maps every pixel back to a bit value by EXACT colour match and
refuses a colour that is not in the palette, naming the pixel. Save as indexed or as 24-bit, either
imports; what matters is the colours.

MULTICOLOUR PIXELS ARE EXPORTED AT THEIR OWN RESOLUTION. On the hardware a multicolour pixel is two
screen columns wide, so the dashboard and the Trumbles look half as wide here as on screen. The
sheet is one pixel per bit pair because that is what round-trips without inventing anything; zoom
in the editor with a 2:1 aspect if it matters.

WHAT THE IMPORT DOES NOT TOUCH. Only the bytes the picture covers are rewritten. The 64th byte of
each sprite definition (padding the hardware never reads, and non-zero noise in the extraction) and
the 2,241st byte of the dashboard picture are kept from the file as it is, and so is every line of
the file that is not a byte literal, which is why a no-op import leaves the file byte-for-byte
unchanged. Pixels outside every picture -- the right half of a multicolour sprite's slot -- are
ignored on the way in.

AN IMPORTED CHANGE IS A DEPARTURE FROM THE ORIGINAL, and the tree is built to notice. These three
files are generated by `tools/extract_tables.py` from the assembled game, `--check` in CI re-derives
them, and `TableTests` compares them against the oracle's memory. Import a changed picture and both
fail, by design (ADR-001 §1: faithful first). This tool does not carry an exemption for that; it
prints the reminder and leaves the decision to whoever changed the art.

Standard library only, like every other script in this folder: the BMP writer and reader are
here because a dependency on an imaging library for three pictures is not worth a rule change
(AGENTS.md §5).
"""

from __future__ import annotations

import argparse
import re
import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GAME_LOGIC = REPO / "GameLogic"

HI_RES = 1  # one bit per pixel, eight pixels a byte, most significant bit leftmost
MULTICOLOUR = 2  # two bits per pixel, four pixels a byte, most significant pair leftmost

# The palette every sheet is written with, index = bit value. Chosen to be told apart at a glance
# and nothing more: 0 is the background, 1 is ink, and 2 and 3 are the two other multicolour
# choices. They are not the game's colours, and the module docstring says why.
PALETTE: list[tuple[int, int, int]] = [
    (0x00, 0x00, 0x00),  # %00 -- background
    (0xFF, 0xFF, 0xFF),  # %01 -- ink
    (0xFF, 0x77, 0x77),  # %10
    (0x70, 0xA4, 0xFF),  # %11
]


class Block:
    """One rectangle of the sheet whose bytes are contiguous rows of the array.

    Byte `column` of row `row` lives at `base + row * row_stride + column`, and a row is
    `byte_columns` bytes wide. A font character is one column and eight rows with a stride of one;
    a sprite is three columns and twenty-one rows with a stride of three. Everything in this file
    is one or the other of those two shapes, but the description does not care.
    """

    def __init__(self, _x: int, _y: int, _byte_columns: int, _rows: int, _bits: int, _base: int, _row_stride: int):
        self.x = _x
        self.y = _y
        self.byte_columns = _byte_columns
        self.rows = _rows
        self.bits = _bits
        self.base = _base
        self.row_stride = _row_stride

    @property
    def pixels_per_byte(self) -> int:
        return 8 // self.bits

    @property
    def width(self) -> int:
        return self.byte_columns * self.pixels_per_byte

    def offset(self, _row: int, _column: int) -> int:
        return self.base + _row * self.row_stride + _column

    def offsets(self) -> list[int]:
        return [self.offset(row, column) for row in range(self.rows) for column in range(self.byte_columns)]


class Bitmap:
    """One array, the file that holds it, and how its bytes tile a sheet."""

    def __init__(self, _identifier: str, _file: str, _length: int, _width: int, _height: int, _blocks: list[Block],
                 _summary: str):
        self.identifier = _identifier
        self.file = _file
        self.length = _length
        self.width = _width
        self.height = _height
        self.blocks = _blocks
        self.summary = _summary

    @property
    def path(self) -> Path:
        return GAME_LOGIC / self.file


def cell_grid(_count: int, _across: int, _bits: int) -> list[Block]:
    """`_count` cells of one byte a row and eight rows, `_across` to a line -- the C64 bitmap's own
    order, in which a cell's eight bytes are consecutive and the cells run left to right and then
    down. The font and the dashboard picture are both this shape."""
    return [Block((index % _across) * (8 // _bits), (index // _across) * 8, 1, 8, _bits, index * 8, 1) for index in range(_count)]


def sprite_row(_modes: list[int]) -> list[Block]:
    """One hardware sprite per 24-pixel slot, left to right: 21 rows of three bytes, then a byte
    of padding the block does not cover. A multicolour sprite is 12 pixels wide and fills the left
    half of its slot."""
    return [Block(index * 24, 0, 3, 21, bits, index * 64, 3) for index, bits in enumerate(_modes)]


# What the tool knows. The shapes come from the arrays' own documentation in LookupTables.h and
# extract_tables.py; the modes of the seven sprites from the two macros that define them
# (`SPRITE2` for the sights and the explosion, `SPRITE4` for the Trumbles -- VideoState.h).
BITMAPS = [
    Bitmap("FONT_DATA", "Font.cpp", 768, 16 * 8, 6 * 8, cell_grid(96, 16, HI_RES),
           "96 characters of 8x8, from space upwards, 16 to a line"),
    Bitmap("DASHBOARD_IMAGE", "DashboardImage.cpp", 2241, 40 * 4, 7 * 8, cell_grid(280, 40, MULTICOLOUR),
           "the dashboard picture, 40 cells by 7 rows, multicolour; the 2,241st byte is not in the picture"),
    Bitmap("SPRITE_DEFINITIONS", "SpriteData.cpp", 448, 7 * 24, 21,
           sprite_row([HI_RES, HI_RES, HI_RES, HI_RES, HI_RES, MULTICOLOUR, MULTICOLOUR]),
           "four laser sights, the explosion cloud (hi-res, 24 wide) and two Trumbles (multicolour, 12 wide)"),
]


def find_bitmap(_name: str) -> Bitmap:
    for bitmap in BITMAPS:
        if bitmap.identifier == _name:
            return bitmap
    known = ", ".join(bitmap.identifier for bitmap in BITMAPS)
    sys.exit(f"error: no bitmap array is called '{_name}' -- the tool knows {known}")


# ---- the array in its .cpp ----------------------------------------------------------------------

BYTE_RE = re.compile(r"0x([0-9A-Fa-f]{2})")


def initializer_span(_text: str, _bitmap: Bitmap) -> tuple[int, int]:
    """Where the array's `= { ... };` sits in the file, so that nothing outside it is touched."""
    match = re.search(rf"\b{re.escape(_bitmap.identifier)}\s*=\s*\{{", _text)
    if match is None:
        sys.exit(f"error: {_bitmap.file} does not define {_bitmap.identifier}")
    end = _text.find("};", match.end())
    if end < 0:
        sys.exit(f"error: {_bitmap.file}: the initializer of {_bitmap.identifier} is not closed")
    return match.end(), end


def read_array(_bitmap: Bitmap, _text: str | None = None) -> bytes:
    text = _bitmap.path.read_text(encoding="utf-8") if _text is None else _text
    start, end = initializer_span(text, _bitmap)
    values = [int(value, 16) for value in BYTE_RE.findall(text[start:end])]
    if len(values) != _bitmap.length:
        sys.exit(f"error: {_bitmap.file}: {_bitmap.identifier} holds {len(values)} byte literals, expected {_bitmap.length}")
    return bytes(values)


def replace_array(_text: str, _bitmap: Bitmap, _data: bytes) -> str:
    """The same file with the byte literals of one array replaced in place -- one for one, so the
    layout clang-format gave the file survives and a no-op import changes nothing."""
    if len(_data) != _bitmap.length:
        sys.exit(f"error: {_bitmap.identifier} takes {_bitmap.length} bytes, not {len(_data)}")
    start, end = initializer_span(_text, _bitmap)
    values = iter(_data)
    body = BYTE_RE.sub(lambda _match: f"0x{next(values):02X}", _text[start:end])
    return _text[:start] + body + _text[end:]


# ---- bytes to pixels and back -------------------------------------------------------------------


def unpack(_bitmap: Bitmap, _data: bytes) -> list[list[int]]:
    """The sheet as rows of bit values, background everywhere no block reaches."""
    pixels = [[0] * _bitmap.width for _ in range(_bitmap.height)]
    for block in _bitmap.blocks:
        per_byte = block.pixels_per_byte
        mask = (1 << block.bits) - 1
        for row in range(block.rows):
            line = pixels[block.y + row]
            for column in range(block.byte_columns):
                value = _data[block.offset(row, column)]
                for pixel in range(per_byte):
                    shift = 8 - block.bits * (pixel + 1)
                    line[block.x + column * per_byte + pixel] = (value >> shift) & mask
    return pixels


def pack(_bitmap: Bitmap, _pixels: list[list[int]], _current: bytes) -> bytes:
    """The array with every byte a block covers rebuilt from the sheet, and every other byte as it
    was. A hi-res block refuses a pixel of 2 or 3: there is no bit to put it in."""
    data = bytearray(_current)
    for block in _bitmap.blocks:
        per_byte = block.pixels_per_byte
        for row in range(block.rows):
            line = _pixels[block.y + row]
            for column in range(block.byte_columns):
                value = 0
                for pixel in range(per_byte):
                    x = block.x + column * per_byte + pixel
                    bit_value = line[x]
                    if bit_value >> block.bits:
                        sys.exit(f"error: pixel ({x}, {block.y + row}) has value {bit_value}, and that part of "
                                 f"{_bitmap.identifier} is hi-res -- only the first two palette colours are allowed there")
                    value = (value << block.bits) | bit_value
                data[block.offset(row, column)] = value
    return bytes(data)


# ---- BMP ----------------------------------------------------------------------------------------

FILE_HEADER = struct.Struct("<2sIHHI")
INFO_HEADER = struct.Struct("<IiiHHIIiiII")
INFO_HEADER_SIZE = 40
BI_RGB = 0
BI_BITFIELDS = 3


def row_stride(_width: int, _bits_per_pixel: int) -> int:
    return ((_width * _bits_per_pixel + 31) // 32) * 4


def encode_bmp(_pixels: list[list[int]], _bits_per_pixel: int = 8) -> bytes:
    """An 8-bit indexed BMP with the four-entry palette, bottom-up as the format prefers. 24-bit
    is here for the self-test, which proves the import reads a true-colour save too."""
    height = len(_pixels)
    width = len(_pixels[0])
    stride = row_stride(width, _bits_per_pixel)
    palette = b""
    if _bits_per_pixel == 8:
        palette = b"".join(struct.pack("<BBBB", b, g, r, 0) for r, g, b in PALETTE)
    rows = []
    for line in reversed(_pixels):
        if _bits_per_pixel == 8:
            row = bytes(line)
        else:
            row = b"".join(struct.pack("<BBB", *reversed(PALETTE[value])) for value in line)
        rows.append(row.ljust(stride, b"\0"))
    pixel_data = b"".join(rows)
    offset = FILE_HEADER.size + INFO_HEADER_SIZE + len(palette)
    info = INFO_HEADER.pack(INFO_HEADER_SIZE, width, height, 1, _bits_per_pixel, BI_RGB, len(pixel_data), 2835, 2835,
                            len(PALETTE) if palette else 0, 0)
    return FILE_HEADER.pack(b"BM", offset + len(pixel_data), 0, 0, offset) + info + palette + pixel_data


def decode_bmp(_blob: bytes, _what: str) -> list[list[tuple[int, int, int]]]:
    """Rows of (r, g, b), top row first, from any uncompressed 1-, 4-, 8-, 24- or 32-bit BMP. What
    it will not read it names, because a picture nobody can import is a picture that was drawn
    for nothing."""
    if len(_blob) < FILE_HEADER.size + INFO_HEADER_SIZE or _blob[:2] != b"BM":
        sys.exit(f"error: {_what} is not a BMP file")
    _, _, _, _, pixel_offset = FILE_HEADER.unpack_from(_blob, 0)
    header_size = struct.unpack_from("<I", _blob, FILE_HEADER.size)[0]
    if header_size < INFO_HEADER_SIZE:
        sys.exit(f"error: {_what} uses an OS/2-style header, which this tool does not read -- save it as a Windows BMP")
    (_, width, height, _, bits_per_pixel, compression, _, _, _, colours_used, _) = INFO_HEADER.unpack_from(_blob, FILE_HEADER.size)
    top_down = height < 0
    height = abs(height)

    masks = (0x00FF0000, 0x0000FF00, 0x000000FF)
    if compression == BI_BITFIELDS and bits_per_pixel == 32:
        masks = struct.unpack_from("<III", _blob, FILE_HEADER.size + INFO_HEADER_SIZE)
    elif compression != BI_RGB:
        sys.exit(f"error: {_what} is compressed (BI_ method {compression}), which this tool does not read -- save it uncompressed")
    if bits_per_pixel not in (1, 4, 8, 24, 32):
        sys.exit(f"error: {_what} is {bits_per_pixel} bits per pixel, which this tool does not read")

    palette: list[tuple[int, int, int]] = []
    if bits_per_pixel <= 8:
        count = colours_used or (1 << bits_per_pixel)
        palette_offset = FILE_HEADER.size + header_size
        for index in range(count):
            b, g, r, _ = struct.unpack_from("<BBBB", _blob, palette_offset + 4 * index)
            palette.append((r, g, b))

    stride = row_stride(width, bits_per_pixel)
    if pixel_offset + stride * height > len(_blob):
        sys.exit(f"error: {_what} is truncated -- the header promises more pixels than the file holds")

    def shift_for(_mask: int) -> int:
        return (_mask & -_mask).bit_length() - 1 if _mask else 0

    rows: list[list[tuple[int, int, int]]] = []
    for line in range(height):
        start = pixel_offset + stride * line
        row: list[tuple[int, int, int]] = []
        for x in range(width):
            if bits_per_pixel == 24:
                b, g, r = _blob[start + 3 * x : start + 3 * x + 3]
                row.append((r, g, b))
            elif bits_per_pixel == 32:
                word = struct.unpack_from("<I", _blob, start + 4 * x)[0]
                row.append(tuple(((word & mask) >> shift_for(mask)) & 0xFF for mask in masks))  # type: ignore[arg-type]
            else:
                per_byte = 8 // bits_per_pixel
                value = _blob[start + x // per_byte]
                shift = 8 - bits_per_pixel * (x % per_byte + 1)
                index = (value >> shift) & ((1 << bits_per_pixel) - 1)
                if index >= len(palette):
                    sys.exit(f"error: {_what}: pixel ({x}, {line}) indexes palette entry {index}, which the file does not define")
                row.append(palette[index])
        rows.append(row)
    return rows if top_down else rows[::-1]


def to_bit_values(_rows: list[list[tuple[int, int, int]]], _bitmap: Bitmap, _what: str) -> list[list[int]]:
    """Colours back to bit values by exact match, and a diagnostic for a colour the palette does
    not have -- the first few of them, so a stray anti-aliased edge is found rather than guessed at."""
    if len(_rows) != _bitmap.height or len(_rows[0]) != _bitmap.width:
        sys.exit(f"error: {_what} is {len(_rows[0])}x{len(_rows)}, and {_bitmap.identifier} is {_bitmap.width}x{_bitmap.height}")
    lookup = {colour: index for index, colour in enumerate(PALETTE)}
    strays: list[str] = []
    pixels: list[list[int]] = []
    for y, row in enumerate(_rows):
        line: list[int] = []
        for x, colour in enumerate(row):
            index = lookup.get(colour)
            if index is None:
                if len(strays) < 8:
                    strays.append(f"({x}, {y}) is #{colour[0]:02X}{colour[1]:02X}{colour[2]:02X}")
                index = 0
            line.append(index)
        pixels.append(line)
    if strays:
        wanted = ", ".join(f"#{r:02X}{g:02X}{b:02X}" for r, g, b in PALETTE)
        sys.exit(f"error: {_what} uses colours that are not in the palette ({wanted}):\n  " + "\n  ".join(strays))
    return pixels


# ---- commands -----------------------------------------------------------------------------------


def do_list() -> int:
    for bitmap in BITMAPS:
        print(f"  {bitmap.identifier:<20} {bitmap.file:<20} {bitmap.width:>3}x{bitmap.height:<3}  {bitmap.summary}")
    return 0


def do_export(_names: list[str], _out: Path) -> int:
    bitmaps = [find_bitmap(name) for name in _names] if _names else BITMAPS
    _out.mkdir(parents=True, exist_ok=True)
    for bitmap in bitmaps:
        target = _out / f"{bitmap.identifier}.bmp"
        target.write_bytes(encode_bmp(unpack(bitmap, read_array(bitmap))))
        print(f"wrote  {target}  ({bitmap.width}x{bitmap.height})")
    return 0


def do_import(_name: str, _source: Path) -> int:
    bitmap = find_bitmap(_name)
    if not _source.is_file():
        sys.exit(f"error: {_source} does not exist")
    pixels = to_bit_values(decode_bmp(_source.read_bytes(), str(_source)), bitmap, str(_source))
    text = bitmap.path.read_text(encoding="utf-8")
    current = read_array(bitmap, text)
    data = pack(bitmap, pixels, current)
    if data == current:
        print(f"unchanged  {bitmap.file}: {_source} holds exactly what {bitmap.identifier} already does")
        return 0
    changed = sum(1 for before, after in zip(current, data) if before != after)
    bitmap.path.write_text(replace_array(text, bitmap, data), encoding="utf-8", newline="\n")
    print(f"wrote  {bitmap.path.relative_to(REPO)}  ({changed} of {bitmap.length} bytes changed)")
    print(f"NOTE   {bitmap.identifier} no longer matches the assembled game: extract_tables.py --check and TableTests\n"
          "       will both say so, and both are meant to (ADR-001). Regenerate to return to the original.")
    return 0


def do_self_test() -> int:
    """Every array, out and back, three ways: the sheet as bit values, the sheet through an 8-bit
    BMP, and the sheet through a 24-bit BMP. Then the file rewrite, which must be the identity on
    an unchanged array, and the two refusals the import promises."""
    import tempfile

    failures = 0

    def check(_condition: bool, _message: str) -> None:
        nonlocal failures
        if not _condition:
            failures += 1
            print(f"FAIL  {_message}")

    for bitmap in BITMAPS:
        # The description is consistent with itself: no byte or pixel is claimed twice, every block
        # sits inside the sheet, and the array is the length the header declares.
        offsets = [offset for block in bitmap.blocks for offset in block.offsets()]
        check(len(offsets) == len(set(offsets)), f"{bitmap.identifier}: two blocks claim the same byte")
        check(max(offsets) < bitmap.length, f"{bitmap.identifier}: a block reaches past the array")
        claimed: set[tuple[int, int]] = set()
        for block in bitmap.blocks:
            check(block.x + block.width <= bitmap.width and block.y + block.rows <= bitmap.height,
                  f"{bitmap.identifier}: a block reaches past the sheet")
            cells = {(x, y) for x in range(block.x, block.x + block.width) for y in range(block.y, block.y + block.rows)}
            check(not (claimed & cells), f"{bitmap.identifier}: two blocks claim the same pixel")
            claimed |= cells

        data = read_array(bitmap)
        pixels = unpack(bitmap, data)
        check(pack(bitmap, pixels, data) == data, f"{bitmap.identifier}: unpack then pack is not the identity")
        for depth in (8, 24):
            decoded = to_bit_values(decode_bmp(encode_bmp(pixels, depth), f"{bitmap.identifier} at {depth} bpp"), bitmap, "self-test")
            check(decoded == pixels, f"{bitmap.identifier}: through a {depth}-bit BMP the sheet came back different")

        text = bitmap.path.read_text(encoding="utf-8")
        check(replace_array(text, bitmap, data) == text, f"{bitmap.identifier}: rewriting the unchanged array altered {bitmap.file}")

        # A one-pixel change lands in exactly one byte, and comes back out.
        block = bitmap.blocks[0]
        altered = [list(line) for line in pixels]
        altered[block.y][block.x] ^= 1
        repacked = pack(bitmap, altered, data)
        check(sum(1 for a, b in zip(repacked, data) if a != b) == 1, f"{bitmap.identifier}: one pixel did not change one byte")
        check(unpack(bitmap, repacked) == altered, f"{bitmap.identifier}: the changed pixel did not survive a round trip")
        check(read_array(bitmap, replace_array(text, bitmap, repacked)) == repacked,
              f"{bitmap.identifier}: the rewritten file does not read back what was written")

    # The import refuses what it says it refuses, and exits rather than guessing (AGENTS.md §5).
    font = BITMAPS[0]
    font_pixels = unpack(font, read_array(font))
    with tempfile.TemporaryDirectory() as folder:
        bad = Path(folder) / "bad.bmp"
        stray = [list(line) for line in font_pixels]
        stray[0][0] = 2
        bad.write_bytes(encode_bmp(stray))
        try:
            pack(font, to_bit_values(decode_bmp(bad.read_bytes(), "bad"), font, "bad"), read_array(font))
            check(False, "a multicolour value in a hi-res block was accepted")
        except SystemExit as error:
            check("hi-res" in str(error), "the hi-res refusal did not say why")

        blob = bytearray(encode_bmp(font_pixels, 24))
        blob[-1] ^= 0x01  # one channel of one pixel, off by one
        try:
            to_bit_values(decode_bmp(bytes(blob), "off-by-one"), font, "off-by-one")
            check(False, "a colour outside the palette was accepted")
        except SystemExit as error:
            check("not in the palette" in str(error), "the palette refusal did not say why")

    if failures:
        print(f"\nFAIL  {failures} self-test(s) failed")
        return 1
    print(f"OK    {len(BITMAPS)} bitmap arrays round-trip through BMP and back into their files unchanged")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--list", action="store_true", help="print the arrays the tool knows")
    parser.add_argument("--self-test", action="store_true", help="prove export then import is the identity, for every array")
    commands = parser.add_subparsers(dest="command")
    export = commands.add_parser("export", help="write one BMP per array")
    export.add_argument("names", nargs="*", help="array names (default: all)")
    export.add_argument("--out", type=Path, default=Path("."), help="directory to write into (default: the current directory)")
    imp = commands.add_parser("import", help="rewrite an array's bytes from a BMP")
    imp.add_argument("name", help="the array name")
    imp.add_argument("file", type=Path, help="the BMP to read")
    args = parser.parse_args()

    if args.list:
        return do_list()
    if args.self_test:
        return do_self_test()
    if args.command == "export":
        return do_export(args.names, args.out)
    if args.command == "import":
        return do_import(args.name, args.file)
    parser.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
