#!/usr/bin/env python3
"""Generate GameLogic/DataOverlay.h, the named data-segment overlay, from Design/Symbols.tsv (ADR-010).

Native code names the reference's data by the symbol table's names (plan §3): it reads
`guest.Get(DS.playerDocked)`, not a byte at 0x75xx. Every DS row of kind data, table or text becomes
one field of `Elite::DataOverlay`, typed from its size and, for a table, from the element type its
contract column gives:

  data, 1 byte         DataField<std::uint8_t>
  data, 2 bytes        DataField<std::uint16_t>
  data, other sizes    DataBlock<bytes>
  table                DataTable<element bytes, entries> when the element type is one this tool can
                       size ("byte", "word", "pointer", "code", "dword", "N-byte ...", "N bytes",
                       "N words", "N characters", "word sin, word cos", "byte pair", "word pair"),
                       else DataAt
  text                 DataBlock<bytes> with a size, else DataAt

The header is generated, never edited: change the symbol table and run this again. With --check it
writes nothing and fails if the header in the tree is not what it would write. Standard library only.

    python Tools/GenerateOverlay.py [--check]
"""

import argparse
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYMBOLS = ROOT / "Design" / "Symbols.tsv"
HEADER = ROOT / "GameLogic" / "DataOverlay.h"
IDENTIFIER = re.compile(r"[a-z][A-Za-z0-9]*")


def element_bytes(_contract: str) -> int | None:
  """The size of one table entry from the element type a table row's contract gives, if it can tell."""
  text = _contract.strip().lower()
  for pattern, scale in ((r"(\d+)-byte\b", 1), (r"(\d+) bytes\b", 1), (r"(\d+) words\b", 2), (r"(\d+) characters\b", 1)):
    match = re.match(pattern, text)
    if match:
      return int(match.group(1)) * scale
  if text.startswith("word sin, word cos"):
    return 4
  if text.startswith("byte pair"):
    return 2
  if text.startswith("word pair") or text.startswith("dword"):
    return 4
  if re.match(r"(byte)\b", text):
    return 1
  if re.match(r"(word|pointer|code)\b", text):
    return 2
  return None


def field_type(_kind: str, _size: str, _contract: str) -> str:
  size = int(_size) if _size.strip() else None
  if _kind == "data":
    if size == 1:
      return "DataField<std::uint8_t>"
    if size == 2:
      return "DataField<std::uint16_t>"
    return f"DataBlock<{size}>" if size else "DataAt"
  if _kind == "table":
    element = element_bytes(_contract)
    return f"DataTable<{element}, {size}>" if element and size else "DataAt"
  return f"DataBlock<{size}>" if size else "DataAt"


ASCII = {"\u2014": "-", "\u2013": "-", "\u00b1": "+-", "\u00d7": "x", "\u00b7": ".", "\u2018": "'", "\u2019": "'",
         "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2192": "->", "\u2265": ">=", "\u2264": "<=", "\u00b0": " degrees"}
MOST_COMMENT_CHARACTERS = 132


def comment(_row: dict[str, str]) -> str:
  """The row's notes (and a table's element type) as one line of ASCII that fits the column limit."""
  parts = [part for part in (_row["contract"].strip() if _row["kind"] == "table" else "", _row["notes"].strip()) if part]
  text = re.sub(r"\s+", " ", "; ".join(parts))
  text = "".join(ASCII.get(character, character) for character in text)
  text = text.encode("ascii", "replace").decode("ascii")
  return text if len(text) <= MOST_COMMENT_CHARACTERS else text[: MOST_COMMENT_CHARACTERS - 3].rstrip() + "..."


def generate() -> str:
  rows = []
  with SYMBOLS.open(encoding="utf-8", newline="") as file:
    lines = [line for line in file if not line.startswith("#")]
  for row in csv.DictReader(lines, delimiter="\t"):
    address = row["address"].strip()
    if not address.startswith("DS:") or row["kind"] not in ("data", "table", "text"):
      continue
    name = row["name"].strip()
    if not IDENTIFIER.fullmatch(name):
      sys.exit(f"GenerateOverlay: {address} is named '{name}', which is not a camelCase identifier")
    rows.append((int(address[3:], 16), name, field_type(row["kind"], row["size"], row["contract"]), comment(row)))
  rows.sort()
  names = [name for _, name, _, _ in rows]
  if len(names) != len(set(names)):
    sys.exit("GenerateOverlay: two data rows share a name")

  out = [
    "// GameLogic/DataOverlay.h",
    "// Generated by Tools/GenerateOverlay.py from Design/Symbols.tsv. Do not edit: change the symbol table",
    "// and run the tool again (ADR-010).",
    "#pragma once",
    "",
    '#include "DataField.h"',
    "",
    "#include <cstdint>",
    "",
    "namespace Elite",
    "{",
    "",
    "/// The reference's data segment by name (plan §3, ADR-010): one field for every data, table and text",
    "/// row of the symbol table, at its offset. Native code reads and writes through Guest with these.",
    "struct DataOverlay",
    "{",
  ]
  for offset, name, kind, note in rows:
    if note:
      out.append(f"  /// {note}")
    out.append(f"  {kind} {name}{{0x{offset:04X}}};")
  out += [
    "};",
    "",
    "/// The overlay native code uses: `DS.playerDocked`.",
    "inline constexpr DataOverlay DS{};",
    "",
    "} // namespace Elite",
    "",
  ]
  return "\r\n".join(out)


def main() -> int:
  parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
  parser.add_argument("--check", action="store_true", help="fail if the header in the tree is out of date")
  arguments = parser.parse_args()
  text = generate()
  if arguments.check:
    current = HEADER.read_bytes().decode("utf-8") if HEADER.exists() else ""
    if current != text:
      print(f"GenerateOverlay: {HEADER.relative_to(ROOT)} is out of date; run python Tools/GenerateOverlay.py")
      return 1
    print("GenerateOverlay: up to date")
    return 0
  HEADER.write_bytes(text.encode("utf-8"))
  print(f"GenerateOverlay: wrote {HEADER.relative_to(ROOT)}")
  return 0


if __name__ == "__main__":
  sys.exit(main())
